### ISSUE TITLE
Fix duplicate and broken Links

### ISSUE THREAD

**Issue by n8225** [Kickball/awesome-selfhosted#1008]
#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

_obsolete report, see below_

**Comment by nodiscc** [comment]
#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
3 | Error | https://chat.awesh.unknownplus.com/channel/awesome-selfhosted <br> SSL_connect returned=1 errno=0 state=error: certificate verify failed
123 | Dupe | http://www.alltubedownload.net 
124 | [502](https://httpstatuses.com/502) | https://amiunique.org/ 
150 | Dupe | https://github.com/jchampemont/WTFDYUM 
162 | Error | http://demo-bludit.rhcloud.com/ <br> Failed to open TCP connection to demo-bludit.rhcloud.com:80 (getaddrinfo: Name or service not known)
168 | Error | https://hotglue.me/ <br> SSL_connect returned=1 errno=0 state=error: certificate verify failed
168 | Error | https://hotglue.me/demo/ <br> SSL_connect returned=1 errno=0 state=error: certificate verify failed
175 | Dupe | https://wordpress.org/ 
175 | Dupe | https://github.com/WordPress/WordPress 
183 | Dupe | https://docs.services.mozilla.com/howtos/run-fxa.html 
190 | [530](https://httpstatuses.com/530) | https://save.duyet.net/ 
238 | Error | http://niltalk.com/ <br> Failed to open TCP connection to niltalk.com:80 (Connection timed out - connect(2) for \"niltalk.com\" port 80)
273 | Dupe | https://github.com/atech/postal 
382 | Error | https://jappix.com/ <br> hostname \"jappix.com\" does not match the server certificate
395 | [503](https://httpstatuses.com/503) | http://www.telescopeapp.org/ 
537 | Dupe | https://github.com/janeczku/calibre-web 
538 | Error | https://blog.slucas.fr/en/oss/calibre-opds-php-server <br> SSL_connect returned=1 errno=0 state=error: certificate verify failed
597 | [502](https://httpstatuses.com/502) | https://winds.getstream.io/ 
636 | [502](https://httpstatuses.com/502) | http://erdgeist.org/gitweb/opentracker/ 
651 | [403](https://httpstatuses.com/403) | http://jirafeau.net/ 
656 | Dupe | https://github.com/ethanal/nimbus 
658 | Dupe | https://www.pictshare.net/ 
679 | Dupe | https://github.com/soyuka/explorer 
680 | Error | https://extplorer.net/ <br> hostname \"extplorer.net\" does not match the server certificate
680 | Error | https://extplorer.net/projects/extplorer/repository <br> hostname \"extplorer.net\" does not match the server certificate
682 | Dupe | https://github.com/xataz/gobrowser 
685 | [403](https://httpstatuses.com/403) | http://mftp.live/ 
702 | Error | https://posio.abrenaut.com/ <br> Net::ReadTimeout
727 | Error | http://demo.mayan-edms.com <br> Failed to open TCP connection to demo.mayan-edms.com:80 (getaddrinfo: Name or service not known)
748 | Dupe | https://www.edx.org/ 
784 | [500](https://httpstatuses.com/500) | https://gnu.io/fm/ 
786 | Dupe | http://www.icecast.org/ 
786 | Dupe | https://git.xiph.org/?p=icecast-server.git;a=summary 
796 | Error | https://darncoyotes.mstream.io/ <br> SSL_connect returned=1 errno=0 state=error: certificate verify failed
828 | Error | https://www.crushpaper.com/ <br> SSL_connect returned=1 errno=0 state=error: certificate verify failed
837 | Error | https://projects.miguelpiedrafita.com/LicAPI <br> Failed to open TCP connection to projects.miguelpiedrafita.com:443 (getaddrinfo: No address associated with hostname)
843 | Error | https://notica.us <br> SSL_connect returned=1 errno=0 state=error: certificate verify failed
859 | [530](https://httpstatuses.com/530) | https://www.budgetapp.io/ 
869 | [500](https://httpstatuses.com/500) | https://invoiceplane.com/ 
878 | Dupe | https://github.com/n1trux/awesome-sysadmin#metric--metric-collection 
913 | Error | http://onlyoffice.org/ <br> bad URI(is not URI?): https:\\\\www.onlyoffice.com
914 | [404](https://httpstatuses.com/404) | http://phpoffice.github.io/ 
942 | Dupe | https://notehub.org 
950 | Error | https://sharppaste.nl/ <br> Failed to open TCP connection to sharppaste.nl:443 (Network is unreachable - connect(2) for \"sharppaste.nl\" port 443)
1002 | Dupe | http://calagator.org/ 
1007 | [404](https://httpstatuses.com/404) | http://kyela.net/55232734237c8/ 
1009 | Dupe | https://github.com/nearbycoder/materialpoll 
1020 | Dupe | https://github.com/thekvs/microproxy 
1021 | Dupe | https://github.com/joshdick/miniProxy/ 
1024 | Dupe | http://www.apsis.ch/pound/ 
1042 | Dupe | http://www.gigablast.com/ 
1061 | Error | https://try.gitea.io <br> Connection reset by peer - SSL_connect
1074 | Error | https://svn.redmine.org/redmine/ <br> SSL_connect returned=1 errno=0 state=error: certificate verify failed
1078 | Dupe | https://github.com/thebuggenie/thebuggenie 
1094 | Dupe | http://micro.glark.io 
1158 | Error | http://demo.taskfreak.com/ <br> Failed to open TCP connection to demo.taskfreak.com:80 (getaddrinfo: Name or service not known)
1159 | Error | https://projects.miguelpiedrafita.com/Tasks/ <br> Failed to open TCP connection to projects.miguelpiedrafita.com:443 (getaddrinfo: No address associated with hostname)
1159 | Error | https://demo.miguelpiedrafita.com/tasks/ <br> Failed to open TCP connection to demo.miguelpiedrafita.com:443 (getaddrinfo: No address associated with hostname)
1199 | [521](https://httpstatuses.com/521) | https://project.polr.me/ 
1230 | Dupe | https://github.com/claudioc/jingo 
1259 | Dupe | http://puffin.rocks/ 
1315 | Error | https://chat.awesome-selfhosted.com <br> Failed to open TCP connection to chat.awesome-selfhosted.com:443 (getaddrinfo: Name or service not known)

**Comment by nodiscc** [comment]
#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
143 | Error | https://archive.sweeting.me <br> hostname \"archive.sweeting.me\" does not match the server certificate
220 | Dupe | https://docs.services.mozilla.com/howtos/run-fxa.html 
275 | Error | https://hubl.in/ <br> Failed to open TCP connection to hubl.in:443 (Connection timed out - connect(2) for \"hubl.in\" port 443)
296 | Error | https://www.syndie.de <br> hostname \"www.syndie.de\" does not match the server certificate
334 | Error | http://www.qmail.org/top.html <br> Failed to open TCP connection to www.qmail.org:80 (getaddrinfo: Name or service not known)
450 | Error | http://demo.telescopeapp.org/ <br> Failed to open TCP connection to demo.telescopeapp.org:80 (Connection timed out - connect(2) for \"demo.telescopeapp.org\" port 80)
451 | Error | https://demo.tokumei.co/ <br> SSL_connect returned=1 errno=0 state=error: certificate verify failed
451 | Error | https://git.tokumei.co/tokumei/tokumei <br> SSL_connect returned=1 errno=0 state=error: certificate verify failed
476 | Error | https://jsxc.org <br> SSL_connect returned=1 errno=0 state=error: certificate verify failed
500 | Error | https://www.apiq.io/ <br> Failed to open TCP connection to www.apiq.io:443 (getaddrinfo: Name or service not known)
500 | Error | http://demo.apiq.io/ <br> Failed to open TCP connection to demo.apiq.io:80 (getaddrinfo: Name or service not known)
511 | [403](https://httpstatuses.com/403) | https://www.drupal.org/ 
520 | Error | http://noosfero.org/ <br> Connection reset by peer
531 | [202](https://httpstatuses.com/202) | https://demo.redaxscript.com/login 
629 | Error | http://leed.idleman.fr <br> Failed to open TCP connection to leed.idleman.fr:80 (getaddrinfo: Name or service not known)
722 | Error | https://sharrydemo.eknet.org <br> Failed to open TCP connection to sharrydemo.eknet.org:443 (getaddrinfo: Name or service not known)
746 | Error | https://gifs.jessfraz.com/ <br> Net::ReadTimeout
757 | Error | http://battlecraft.online <br> Failed to open TCP connection to battlecraft.online:80 (Connection timed out - connect(2) for \"battlecraft.online\" port 80)
762 | Error | https://posio.abrenaut.com/ <br> hostname \"posio.abrenaut.com\" does not match the server certificate
879 | Error | http://www.fomori.org/cherrymusic/ <br> Failed to open TCP connection to www.fomori.org:80 (Connection timed out - connect(2) for \"www.fomori.org\" port 80)
909 | Error | https://osptest.divby0.net <br> SSL_connect returned=1 errno=0 state=error: certificate verify failed
912 | Dupe | https://gitlab.com/Shinobi-Systems/ShinobiCE 
929 | Error | http://easybook-project.org/ <br> Failed to open TCP connection to easybook-project.org:80 (getaddrinfo: Temporary failure in name resolution)
941 | Error | https://nnmm.nl/ <br> Failed to open TCP connection to nnmm.nl:443 (getaddrinfo: Name or service not known)
943 | [522](https://httpstatuses.com/522) | https://demo.ombi.io/ 
979 | [500](https://httpstatuses.com/500) | https://demo.silverstrike.org/ 
1048 | Error | https://bin.doyle.la <br> Failed to open TCP connection to bin.doyle.la:443 (Network is unreachable - connect(2) for \"bin.doyle.la\" port 443)
1056 | Dupe | https://github.com/LINKIWI/modern-paste 
1062 | Error | https://ptpb.pw/ <br> Failed to open TCP connection to ptpb.pw:443 (getaddrinfo: No address associated with hostname)
1065 | Error | https://sharppaste.nl/ <br> Failed to open TCP connection to sharppaste.nl:443 (getaddrinfo: Name or service not known)
1154 | Error | https://banu.com/tinyproxy/ <br> Failed to open TCP connection to banu.com:443 (Network is unreachable - connect(2) for \"banu.com\" port 443)
1216 | Error | https://svn.redmine.org/redmine/ <br> SSL_connect returned=1 errno=0 state=error: certificate verify failed
1236 | Error | http://micro.glark.io <br> Failed to open TCP connection to micro.glark.io:80 (getaddrinfo: Name or service not known)
1238 | Error | https://requestb.in/ <br> Failed to open TCP connection to requestb.in:443 (Connection timed out - connect(2) for \"requestb.in\" port 443)
1324 | Error | https://getbrimir.com/ <br> Failed to open TCP connection to getbrimir.com:443 (getaddrinfo: Name or service not known)
1341 | Error | http://sit-it.org/ <br> Failed to open TCP connection to sit-it.org:80 (getaddrinfo: Name or service not known)
1349 | [404](https://httpstatuses.com/404) | https://devshort.florian-kaldowski.de 
1352 | Error | https://linkrapp.com <br> Failed to open TCP connection to linkrapp.com:443 (getaddrinfo: Name or service not known)
1352 | Error | https://demo.linkrapp.com <br> Failed to open TCP connection to demo.linkrapp.com:443 (getaddrinfo: Name or service not known)
1384 | Error | https://demo.django.wiki/ <br> Failed to open TCP connection to demo.django.wiki:443 (Connection timed out - connect(2) for \"demo.django.wiki\" port 443)
1403 | [404](https://httpstatuses.com/404) | https://docs.requarks.io/wiki 
1421 | Error | https://piratebox.cc/start <br> SSL_connect returned=1 errno=0 state=error: certificate verify failed
1422 | Error | http://puffin.rocks/ <br> Failed to open TCP connection to puffin.rocks:80 (Connection refused - connect(2) for \"puffin.rocks\" port 80)
1466 | Error | https://www.isc.org/downloads/software-support-policy/isc-license/ <br> Failed to open TCP connection to www.isc.org:443 (getaddrinfo: Temporary failure in name resolution)

**Comment by nodiscc** [comment]
Moved to https://github.com/Kickball/awesome-selfhosted/issues/1767
