### ISSUE TITLE
Tools: document test.js

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#1012]
Followup to #875

@n8225  Can you document the test.js file a bit? Ideally with comment blocks for each function/...

```
/*!
 * What the function does
 * \fn function(example, others)
 * \param string example An example parameter
 * \param array others (optional) An array of optional parameters
 * \return string Value returned by this function
 */
```

I have very little experience of JavaScript and a properly commented script will make maintenance/modification/comprehension of this script easier.

**Comment by Kickball** [comment]
This has been documented in #1024.
