### ISSUE TITLE
Require more information if ⚠ is added to a project?

### ISSUE THREAD

**Issue by e-alfred** [Kickball/awesome-selfhosted#1020]
Hello,

would it be possible to require more information to be added if ⚠ is added to some project? This would make it easier for viewers to find out what external service/component is needed that the user can't control.

**Comment by cpdevelops** [comment]
I think that is a great idea. It could come after the name of the project so that if someone sees this: ⚠  they can go find out more information themselves and also be contributing to the project.

**Comment by nodiscc** [comment]
Reasons for marking a project with the ⚠ symbol are listed in corresponding issues/pull requests. Usually you can just [search for the project in the issues tracker](https://github.com/Kickball/awesome-selfhosted/issues/) to go back to discussion surrounding that project.

Eg. https://github.com/Kickball/awesome-selfhosted/issues?q=poffer returns https://github.com/Kickball/awesome-selfhosted/pull/739 which has more information about the Poffer ⚠ entry.

I don't think the markdown file itself is appropriate to detail that kind of info (we try to keep it readable by not stuffing it with details, it's already quite large).

Is there software which is marked ⚠ for an unclear reason? If that info is missing, we can add it to the relevant archived pull request/issue.

**Comment by nodiscc** [comment]
Closing, feel free to reopen if needed. Referencing in #89

**Comment by melvinmezzy** [comment]
> Hello,
>help wanted 
> 
> ![image](https://user-images.githubusercontent.com/98871913/154001766-d552d365-342d-4dd3-a050-5e6756044c88.png)
> would it be possible to require more information to be added if ⚠ is added to some project? This would make it easier for viewers to find out what external service/component is needed that the user can't control.
