### ISSUE TITLE
Add Zarafa groupware

### ISSUE THREAD

**Issue by e-alfred** [Kickball/awesome-selfhosted#1029]
Hello,

please add Zarafa Groupware as an Open Source project:

https://community.zarafa.com/

**Comment by fbartels** [comment]
Hi, the list already features Kopano which is a fork of Zarafa (done by the same people). Zarafa will only receive limited updates in the future, so the general recommendation is to look at Kopano instead.

**Comment by nodiscc** [comment]
Hi, the "Pricing" page on zarafa.com points to https://kopano.com/pricing?ref=zarafa&type=pricing, which in turn points to https://stash.kopano.io/repos?visibility=public. I think it's safe to close this issue (we already list kopano and there is no other available source code link for zarafa).

Feel free to reopen if needed
