### ISSUE TITLE
Add Runalize

### ISSUE THREAD

**Issue by 315i** [Kickball/awesome-selfhosted#1030]
Runalyze is a web application for analyzing your training - more detailed than any other sports diary. We are offering a official hosted version at runalyze.com.

https://github.com/Runalyze/Runalyze/

The project is licensed under the Apache license.

**Comment by Kickball** [comment]
Does Runalyze have a license @315i, I can't find it on the project?

**Comment by cpdevelops** [comment]
@Kickball Just searched through the project, it is licensed under Apache. If you search license while in the repository it will show every instance of it in every file.

Hope this helps!

**Comment by Kickball** [comment]
Thanks @cpdevelops, I've edited the original issue to include this detail.

**Comment by Kickball** [comment]
@315i @cpdevelops @nodiscc what category would this best fit in? Analytics? Automation?

**Comment by cpdevelops** [comment]
@Kickball I have not used the application myself, only skimmed through the code files after seeing this issue. 

Based off @315i 's original comment I think that it might work best in Analytics. 

> Runalyze is a web application for **analyzing** your training

I do not have a chance to look at all the categories right now, but is there one for something similar to a information storage system? It could also go there.

> ...more than any other sports diary.

**Comment by nodiscc** [comment]
There are similare entries (wger...) in https://github.com/Kickball/awesome-selfhosted#personal-dashboards.

This section could use some cleanup/reorganization in the future.

**Comment by Kickball** [comment]
I'll add it to personal dashboards for now then. Thanks @nodiscc.

**Comment by 315i** [comment]
thanks @Kickball Runalize is training/fitness analytic tool, but personal dashboards is also fine as there are similar apps.

**Comment by worldworm** [comment]
Can be closed
The repository has been archived by the owner. It is now read-only.

**Comment by nodiscc** [comment]
Thanks
