### ISSUE TITLE
Remove Grafana, Dashing, Freeboard (awesome-sysadmin duplicates)

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#1036]
Grafana, Dashing, Freeboard (https://github.com/Kickball/awesome-selfhosted#personal-dashboards) are already listed at https://github.com/n1trux/awesome-sysadmin#metric--metric-collection

 - [x] remove Grafana, Dashing, Freeboard
 - [x] add _See https://github.com/n1trux/awesome-sysadmin#metric--metric-collection_ on top of _Personal Dashboards_ section.
 - Add _For personal analytics/dashboards, see [Personal Dashboards](https://github.com/Kickball/awesome-selfhosted#personal-dashboards)_ on top of _Analytics_ section.

**Comment by Kickball** [comment]
These were both added in #1037.
