### ISSUE TITLE
add feed2imap

### ISSUE THREAD

**Issue by pintman** [Kickball/awesome-selfhosted#1039]
From their website:
"feed2imap (http://home.gna.org/feed2imap/) is an RSS/Atom feed aggregator. After Downloading feeds (over HTTP or HTTPS), it uploads them to a specified folder of an IMAP mail server or copies them to a local maildir. The user can then access the feeds using Mutt, Evolution, Mozilla Thunderbird or even a webmail."

**Comment by worldworm** [comment]
I think the project is abandoned.
The homepages throws an 404, and the last commit is from 9 Jun 2015
https://github.com/feed2imap/feed2imap

**Comment by pintman** [comment]
Sad but true. I will close the issue.

worldworm schrieb am 14.08.19 um 17:36:
