### ISSUE TITLE
add passbolt

### ISSUE THREAD

**Issue by Kulak** [Kickball/awesome-selfhosted#1050]
<https://www.passbolt.com>

**Comment by Kulak** [comment]
The project might not be a good candidate for selfhosted.

It requires installation of browser extension to work with it.  I am not sure if extension if free.

**Comment by Kickball** [comment]
[Passbolt](https://www.passbolt.com/) - Free, open source, extensible, Password Manager based on OpenPGP. Open source Chrome and Firefox extensions are required. ([Demo](https://demo.passbolt.com/auth/login), [Source Code](https://github.com/passbolt/passbolt_api)) `AGPLv3` `PHP`

Thanks for your recommendation @Kulak. Regarding your concern of a required browser extension, we use '⚠' to signify that a project depends on a third party service. This can be used for this project, however, it is debatable whether it is required, as the [browser extensions are also open sourced](https://github.com/passbolt/passbolt_browser_extension).

@nodiscc do you want to weigh in on this?

**Comment by nodiscc** [comment]
Hi, as long as all the components are Free Software I don't see a reason to reject it or mark it ⚠ (since the user has control over all the components)
