### ISSUE TITLE
Conference Management  bigbluebutton

### ISSUE THREAD

**Issue by Edtigoza** [Kickball/awesome-selfhosted#1070]
Hi...
 you can add to the Conference Management
BigBlueButton provides real-time sharing of audio, video, slide, chat, and screen.

demo :   https://demo.bigbluebutton.org/
source :  https://github.com/bigbluebutton/bigbluebutton
site :   https://bigbluebutton.org/

**Comment by Kickball** [comment]
Added in #1575.
