### ISSUE TITLE
Add LibreRead: Self-hosted free(Libre) ebook reader

### ISSUE THREAD

**Issue by mysticmode** [Kickball/awesome-selfhosted#1077]
https://github.com/mysticmode/LibreRead
http://libreread.org

**Comment by mysticmode** [comment]
The repo has been moved to https://savannah.nongnu.org/projects/libreread/

When will this be added?

**Comment by Kickball** [comment]
Sorry @mysticmode but there is a backlog of issues. Please feel free to submit a PR for it, otherwise, it will be handled when possible.

**Comment by meitar** [comment]
Added in 85be66fb37bb6ea9cc8fc167b9a611b90848fcaa. This issue should be closed now.

Ping @nodiscc.
