### ISSUE TITLE
Add WonderCMS

### ISSUE THREAD

**Issue by robiso** [Kickball/awesome-selfhosted#1087]
[WonderCMS](https://www.wondercms.com/) - WonderCMS is the smallest flat file CMS since 2008. ([Demo](https://www.wondercms.com/demo), [Source Code](https://github.com/robiso/wondercms))
License: [MIT](https://github.com/robiso/wondercms/blob/master/license)
`Language: PHP and jQuery`
`Free, without any additional/hidden costs`

**Comment by nodiscc** [comment]
https://github.com/robiso/wondercms/blob/master/license MIT

**Comment by robiso** [comment]
@nodiscc thank you, updated my comment to link to the license.
