### ISSUE TITLE
Add Zevenet

### ISSUE THREAD

**Issue by fedelebrero** [Kickball/awesome-selfhosted#1088]
[Zevenet](https://www.zevenet.com/) - Multilayer open source load balancer ([Source Code](https://github.com/zevenet))
License: GNU Lesser General Public License v2.1
Language: Perl

**Comment by nodiscc** [comment]
@fedelebrero it looks nice, but it would probably be better to submit it to https://github.com/n1trux/awesome-sysadmin#web (next to HAProxy/Varnish maybe)
