### ISSUE TITLE
Add Filerun

### ISSUE THREAD

**Issue by Blackphidora** [Kickball/awesome-selfhosted#1090]
http://www.filerun.com/

**Comment by Blackphidora** [comment]
File sharing system that focuses on pluging into existing folders

**Comment by formatme** [comment]
was wondering why this inst already on the list :P

**Comment by cpdevelops** [comment]
Hey there @Blackphidora. I am trying to make a pull request to add this to the list, but cannot seem to find the information on the license and language written in. If you could provide me with that information that would be great.

**Comment by nodiscc** [comment]
@cpdevelops Filereun is proprietary/closed source software and therefore should be added to `non-free.md`. You won't find any source code or FOSS license info on their site.

**Comment by mightyfree** [comment]
Filerun was added to proprietary list in Pull #798. This issue can be closed.

**Comment by Kickball** [comment]
Thanks @mightyfree.
