### ISSUE TITLE
add DietPi

### ISSUE THREAD

**Issue by DJCrashdummy** [Kickball/awesome-selfhosted#1094]
_i'm not sure if DietPi should be added and if yes, wether it really fits the "[Self-hosting Solutions](https://github.com/Kickball/awesome-selfhosted#self-hosting-solutions)" section or an other one... so i just opened this issue._

DietPi is a small lightweight debian optimized for ~30 and counting single-board computers (images for VirtualBox and VMware are also available):
- the installation can be automatized by simply editing a txt-file
- it uses just shell-scripts, so no special software is required
- customizing, backup, update and installing/uninstalling new "ready-to-run" software is easily done with GUI-like shell dialogues.

DietPi is maybe not a single service you are looking for, but if you want to selfhost something at home, or you just want to play around with a service before setting it up on your production server, DietPi is nice to have and wether you are an expert or beginner really eases some things.

the line - added wherever - should look something like that... i'm not sure if the description is (good) enough to point out scope and advantages of the project:
> [DietPi](http://dietpi.com/) - Highly optimized extremely lightweight minimal Debian OS, which allows you to get the maximum performance from your single-board computer. ([Source Code](https://github.com/Fourdee/DietPi)) `GPLv2` `Shell`

**Comment by nodiscc** [comment]
It looks interesting but is not related to self-hosted network services; for anyone wondering it's an alternative to Raspbian (OS image/distribution for Raspberry Pi). I understand it can be used as a base to setup Pi-based servers, but we're not going to list it (else we would have to list every Linux distribution). @DJCrashdummy I hope that's fine, thanks for bringing it up.

**Comment by DJCrashdummy** [comment]
- DietPi is not just an OS:
please have a look at [this list](http://dietpi.com/phpbb/viewtopic.php?f=8&t=5#p5) of some ready-to-run software (i know there are also some desktop-environments, but most of the software can also/only be used as server via webGUI, etc.)
> customizing, backup, update and installing/uninstalling new "ready-to-run" software is easily done with GUI-like shell dialogues.

- it is not just for Raspbian:
> optimized for ~30 and counting single-board computers

additional i had a closer look a the "[Self-hosting Solutions](https://github.com/Kickball/awesome-selfhosted#self-hosting-solutions)" section and don't see big differences to _Freedombone_, _UBOS_ or _DPlatform_.
maybe the biggest is, that DietPi is focused on single-board computers (and supports by far the biggest variety compared with the other projects), but in my eyes this is a good thing for self-hosting.

although DietPi has no webGUI, it is also pretty similar to _FreedomBox_ (also smaller hardware-support) or _Sandstorm_ (just for full-powered servers).

sooo... i'm sorry, that i have to reply, but i don't see a clear inclusion policy.

_PS: maybe the short description in the line for inclusion does not completely hit the point!_

**Comment by e-alfred** [comment]
It is mostly based on the way better Armbian distribution and allows to install many selfhosted applications which are listed on this list too with a single script:

http://dietpi.com/phpbb/viewtopic.php?f=8&t=5#p5

The Armbian community helps to make many of the supported boards running way more secure operating systems with a huge community effort that is very helpful for everyone. The images/software provided by manufacturers like Allwinner and so on are shoddy, outdated and littered with creepy vulnerabilities (an enabled debug interface that allows complete takeover for example) or just don't function well/have no sane documentation.

Dietpi takes their work and combines it with an easy to use way to install a lot of applications for selfhosting, just as this Awesome list here does list them. All in all, Dietpi makes it easy to get more people to selfhost their stuff in a more secure way which is quite in line with this list.
