### ISSUE TITLE
owncloud-apps and nextcloud-apps

### ISSUE THREAD

**Issue by DJCrashdummy** [Kickball/awesome-selfhosted#1095]
wether remove single owncloud-apps, since they aren't usable standalone, since it won't make sense to add several owncloud/nextcloud-apps...!?

or at least add/mention the nextcloud-equivalent for the 2 owncloud-apps (calendar & documents), which are listed now.

**Comment by nodiscc** [comment]
We should probably remove owcnloud apps. There are so many of them and we only list 2.

**Comment by e-alfred** [comment]
How about putting a link to the respective stores? Especially the Nextcloud store at https://apps.nextcloud.com has a nice list of basically only Open Source apps for it. Otherwise, I think they should go to a seperate awesome list dealing specificially with Owncloud/Nextcloud.

**Comment by DJCrashdummy** [comment]
i think at least linking is a good idea, since the nextcloud app-store contains apps with [only AGPLv3, MPL 2.0 or Apache License 2.0](https://nextcloudappstore.readthedocs.io/en/latest/developer.html#info-xml).

but for the owncloud app-store i'm not sure:...
- for the old deprecated one (https://apps.owncloud.com/) i don't think there is/was such a restriction (it was always a bit of a mess).
- and about the new one (https://marketplace.owncloud.com/) i have no clue, but it looks like they are planing to add commercial (closed source) apps.

**Comment by nodiscc** [comment]
Since many listed projects support some kind of "app store" (notably groupwares and self-hosting solutions), listing them all would be cumbersome and would clutter the list (it is already quite large). It is better to let each project advertise their app store on their website or documentation.
