### ISSUE TITLE
Rocketchat down

### ISSUE THREAD

**Issue by higgs01** [Kickball/awesome-selfhosted#1117]
Rocketchat at https://chat.awesome-selfhosted.com/ seems to be offline
Error: `DNS_PROBE_FINISHED_NXDOMAIN`

**Comment by ToeiRei** [comment]
Looks like a dns problem to me

**Comment by nodiscc** [comment]
My guess is that @arylatt / @Kickball forgot to renew the domain name :)

**Comment by nodiscc** [comment]
Fixed in https://github.com/Kickball/awesome-selfhosted/pull/1151

New URL is https://chat.awesh.unknownplus.com/channel/awesome-selfhosted

**Comment by evaryont** [comment]
FYI, the [contributing guidelines](https://github.com/Kickball/awesome-selfhosted/blob/master/.github/CONTRIBUTING.md) still link to the old URL.
