### ISSUE TITLE
Add Bittytorrent

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#1127]
https://github.com/atmoner/Bittytorrent
https://github.com/kickball/awesome-selfhosted#peer-to-peer-filesharing
Php Bittorrent CMS https://bittytorrent.com/
PHP
GPLv3

**Comment by cpdevelops** [comment]
The website (bittytorrent.com) seems to be down. Is there anything needed there for the listing? I'm planning on making a PR that addresses many of the addition issues.

**Comment by nodiscc** [comment]
@cpdevelops the site is up but currently misconfigured (`SSL_ERROR_RX_RECORD_TOO_LONG`) over HTTPS, and plain HTTP access shows a default CentOS control panel page. Let's wait a week or so to see if it gets fixed, otherwise just linking to the source code would be fine.

**Comment by atmoner** [comment]
Done! Forum is online and projet is update

**Comment by Kickball** [comment]
There looks to be an issue with the site at the moment ([Bittytorrent#15](https://github.com/atmoner/Bittytorrent/issues/15)) but the project has been recently maintained so I'm happy to for this issue to be kept open for now.

**Comment by n8225** [comment]
Do we want to leave the issue open?

**Comment by nodiscc** [comment]
Nope. Unfortunately closing this because the project looks unmaintained. See https://github.com/Kickball/awesome-selfhosted/pull/1576. The world needs a decent FOSS torrent site CMS  :/

**Comment by Kickball** [comment]
I don't see a large amount of activity from the owner of the repository so I'm happy for this to be closed.

**Comment by Kickball** [comment]
Oops
