### ISSUE TITLE
Add HRCloud2

### ISSUE THREAD

**Issue by zelon88** [Kickball/awesome-selfhosted#1136]
Hello there!

I maintain the GPLV3 [HRCloud2](https://github.com/zelon88/HRCloud2) project on Github and would really like to see it get added to your list. 

Perhaps we could put it with ownCloud, NextCloud and the like under "File Sharing / Synchronization?"

**Comment by Kickball** [comment]
That location seems like it would fit quite well. @nodiscc what is your view?

Also a note @zelon88 there is a bit of a backlog of issues at the moment, so if you want this adding soon your best bet would be to submit a PR.

**Comment by nodiscc** [comment]
https://github.com/Kickball/awesome-selfhosted#groupware looks like a better fit to me.

Be wary of using [shell_exec](https://github.com/zelon88/HRCloud2/search?utf8=%E2%9C%93&q=shell_exec&type=Code). @zelon88 is this widely deployed/are there known security issues? Otherwise ok to add

**Comment by zelon88** [comment]
Thanks, guys!

The shell_exec's should all be either hard-coded, escaped, or sanitized of dangerous characters for safety.

I wouldn't call it "widely" deployed but it gets decent traffic and 8x 3rd party forks. 

I am not currently aware of any security issues, but we're constantly on the lookout and it gets updated regularly (new features/improvements several times per week).

Thank you for your time!
zelon88
