### ISSUE TITLE
Awesome Badge Display

### ISSUE THREAD

**Issue by Kickball** [Kickball/awesome-selfhosted#114]
[Awesome](https://github.com/sindresorhus/awesome) has requested in their issue [253](https://github.com/sindresorhus/awesome/issues/253) that awesome lists on their list show [this badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).

[![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome)

I don't see a problem doing this, but I don't want to end up with more than 1 or 2 buttons for lists containing out list.

What do you think @nodiscc?

**Comment by nodiscc** [comment]
No problem for me either. Can you add it on a single line between the title and description (line 2-3)?

**Comment by Kickball** [comment]
Added in #115.

**Comment by Kickball** [comment]
@nodiscc awesome has requested that we put it to the right of the title, what do you think?

It doesn't make too much of a difference to me where it is put.

**Comment by nodiscc** [comment]
The markdown file should remain readable when viewed as plain text (one of the properties of markdown). Adding `[![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome)` there makes the title hard to understand in plain-text.

`# Title` blocks are for titles so it should remain as is, IMHO.

**Comment by Kickball** [comment]
Makes sense, I hadn't thought of that.

In summary we're adding the badge, however we're putting it between the title and the project's description.
