### ISSUE TITLE
Add EasyAppointments and Alfio (Booking applications)

### ISSUE THREAD

**Issue by luxlogica** [Kickball/awesome-selfhosted#1178]
The 'Calendaring' category does not seem to include **booking** apps - i.e., self-hosted apps that might be good substitutes for services like [Accuity Scheduling](https://acuityscheduling.com), [YouCanBookMe](https://youcanbook.me) or [vCita](https://www.vcita.com). 

I can think of only one atm - [EasyAppointments](http://easyappointments.org) - but I know there are dozens, from generic ones through to some that specialise in vertical markets (e.g., restaurant bookings, hotel/holiday bookings, health clinic bookings, event/workshop bookings, etc.).

**Comment by nodiscc** [comment]
@luxologica can you send a Pull Request for EasyAppointments?

Renaming the issue to address this in particular.

> but I know there are dozens, from generic ones through to some that specialise in vertical markets

That would be nice to have if you can point us to these projects. When there are 3 or more of these booking apps in the list we can move them to a separate _Booking_ subsection.

**Comment by luxlogica** [comment]
@nodiscc - I've come across a few of these by accident in the past, but as usual, when you actually want to find them, you can't! 🙄 

In any case, I do remember __[Alfio](https://alf.io)__ , a free, open-source event-booking system, which can be used to sell tickets online. 

As I come across other solutions, I'll post them here for future reference, and perhaps, addition to the list. ;-)

**Comment by worldworm** [comment]
Alf.io and Easy!Appointments are added. I think this issue can be closed.
