### ISSUE TITLE
[Question] Flowchart-like apps?

### ISSUE THREAD

**Issue by Maxiride** [Kickball/awesome-selfhosted#1179]
While browsing github I found [this](https://github.com/kamranahmedse/developer-roadmap) repo with wonderful flowcharts. At the end of the page they say that they have used https://balsamiq.com . I've never saw a service like that before so this might be a very very silly question :confused:

Are there self-hosted apps like that? To make diagrams\flowcharts\maps etc basically content organized by boxes\trees\line links etc. Not necessarily for roadmaps of a project but maybe also to summarize university books or notes, I'm inedeed mixing up some stuff since the idea is a general purpose thing.

Edit: After some rounds of searching I found https://coggle.it, that might help in shaping the concept I'm referring to.

**Comment by poVoq** [comment]
draw.io can do that I guess?

**Comment by nodiscc** [comment]
[draw.io](https://github.com/jgraph/drawio) (not on the list yet), [mindmaps](https://github.com/drichard/mindmaps), or [Dia](https://en.wikipedia.org/wiki/Dia_%28software%29) (desktop software - Linux/win) can help you draw such charts. I've been using Dia to chart (rather large) hardware/connections charts and it worked out well.

If you can't find what you're looking for, you may want to ask on https://www.reddit.com/r/selfhosted/, I'm sure there will be people willing to help.

**Comment by Maxiride** [comment]
Thanks for all the insights provided! I'll check them out ;)
