### ISSUE TITLE
BrowserID / Mozilla Persona

### ISSUE THREAD

**Issue by Kickball** [Kickball/awesome-selfhosted#118]
Hey,

I might have missed something, but how is this related to self-hosting? It seems like the logins go through Mozilla, and I can't find the source code anywhere.

We might need to transfer this to the non-free list.

* [BrowserID/Mozilla Persona](https://developer.mozilla.org/en-US/Persona/Identity_Provider_Overview)

**Comment by nodiscc** [comment]
You can definitely self-host your Identity Provider. Instructions on how to do so are lacking, though. https://developer.mozilla.org/en-US/Persona/Implementing_a_Persona_IdP and https://github.com/mozilla/persona may provide a good starting point.

We should link to an usable implementation of the IdP server and add language and licenses tags for the `BrowserID/Mozilla Persona` entry.

**Comment by Kickball** [comment]
I've attempted to get our Persona listing to a better state in bca2576

**Comment by Kickball** [comment]
All we are missing from this now is a description of the service.

**Comment by AndyR207** [comment]
Persona is no longer developed and will be shut down completely as of Nov. 30th 2016
