### ISSUE TITLE
Move Movim to XMPP?

### ISSUE THREAD

**Issue by poVoq** [Kickball/awesome-selfhosted#1187]
Right now Movim is mentioned under "Social Networks and Forums", while it is in fact more of an XMPP web-client with some neat additional features.

It would be much more suitable under the "XMPP Web Clients" heading.

**Comment by nodiscc** [comment]
@poVoq qure, canyou sennd a Pull Request?

**Comment by poVoq** [comment]
https://github.com/Kickball/awesome-selfhosted/pull/1190
