### ISSUE TITLE
`make contrib` issues on macOS

### ISSUE THREAD

**Issue by quinncomendant** [Kickball/awesome-selfhosted#1195]
`make contrib` doesn't work on macOS. There are two issues that *involve macOS and other BSD-derived versions of `sed`*:

1. `sed -i` requires specifying an extension, even if blank. Use this: `sed -i ''`.
2. `sed` doesn't accept `\t` as a notation for the TAB character. This works for bash shells: `$'s/\t/ | /g'`

Putting this together, the sed command in the `contrib` command should be:

    sed -i '' $'s/\t/ | /g' AUTHORS.md

**Comment by Kickball** [comment]
@nodiscc I am not familiar with bash/makefiles, I am happy with this change if you are.

@quinncomendant thank you for highlighting this issue.

**Comment by nodiscc** [comment]
@quinncomendant Thank you for raising this. I have tried applying your change, and am getting an error (using GNU Bash 4.4.12 and GNU sed 4.4 on Debian):

```
$ make contrib 
/bin/bash: -c: line 0: unexpected EOF while looking for matching `''
/bin/bash: -c: line 1: syntax error: unexpected end of file
Makefile:33: recipe for target 'contrib' failed
make: *** [contrib] Error 1
```

Do you know of a way to make this work on all platforms?

**Comment by nodiscc** [comment]
The makefile only supports GNU Bash.
