### ISSUE TITLE
Does it make sense to have an archive/attic of removed projects?

### ISSUE THREAD

**Issue by evaryont** [Kickball/awesome-selfhosted#1200]
I think there is some value in cataloging not only the current awesome self-hosting projects, but also those that have come and gone. So perhaps an 'ATTIC.md' file could be added with similar categories as README but contains those that don't meet the criteria. Include a warning at the top of the file, and it could be a useful historical artifact.

**Comment by evaryont** [comment]
@nodiscc what do you think about extending #1038? Add a flag `archived: true/false` to the schema, and have the .md be a generated result. That'd make the makefile scripting much simpler.

**Comment by nodiscc** [comment]
@evaryont yes this is another case for a machine-readable list format. With the right filtering tools, we could easily hide entries that have an old `last_update:` value, or that have `maintained: false`, etc... 

I'll move this to #1038 then
