### ISSUE TITLE
[Question] Invoice\Budget\Financial with bank account integration

### ISSUE THREAD

**Issue by Nixellion** [Kickball/awesome-selfhosted#1241]
Hello,

I wonder if there's some self-hosted financial app which can track your money movements from bank account? Or do they all work in a way that you have to input everything manually?

The question is if such thing even exists, or is it a security flaw and there is no way you can see your money but through bank websites and apps?

I'm sorry if it's the wrong place to ask.

**Comment by ma7dy** [comment]
You need something open source similar to https://www.mint.com , I think you can use GNUcash which supports directly connecting to banks https://wiki.gnucash.org/wiki/OFX_Direct_Connect_Bank_Settings#General_instructions

**Comment by nodiscc** [comment]
@Nixellion I used to use [Homebank](http://homebank.free.fr/en) (desktop application), combined with [boobank](http://weboob.org/applications/boobank) - a scriptable command-line tool to fetch bank account balances, most recent movements, etc.. to CSV or other formats. You need an application that can consume one of boobank's output formats (look in https://github.com/Kickball/awesome-selfhosted#money-budgeting-and-management or as we said, GNUcash or Homebank are fine, but desktop based).

Please let us know if this solves your problems

**Comment by nodiscc** [comment]
1 month without updates, closing.
