### ISSUE TITLE
Use SPDX license identifiers for easier portability and interoperability during parsing.

### ISSUE THREAD

**Issue by meitar** [Kickball/awesome-selfhosted#1268]
The Software Package Data Exchange defines standardized identifiers for various different software licenses. The Awesome Selfhosted list does not use these, but probably should.

**Comment by evaryont** [comment]
This is something that I wanted to tackle along with the rest of the machine-readable work in #1038

**Comment by nodiscc** [comment]
This is fixed in @meitar's Pull Request https://github.com/Kickball/awesome-selfhosted/pull/1269, I need to find a way to split the patch into reviewable units.

**Comment by nodiscc** [comment]
Done.
