### ISSUE TITLE
Reduce overlap with awesome-sysadmin

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#127]
Followup to https://github.com/Kickball/awesome-selfhosted/pull/81; our list currently overlaps with @n1trux's https://github.com/n1trux/awesome-sysadmin in many areas. To prevent overlap, avoid NIH syndrome and decrease maintenance on the 2 lists, I suggest merging some of our lists sections as follows:

Import and remove from awesome-sysadmin:
- [x] copy https://github.com/n1trux/awesome-sysadmin#project-management
  - [x] remove section from awesome-sysadmin
- [x] copy https://github.com/n1trux/awesome-sysadmin#statistics
  - [x] remove sectrion from awesome-sysadmin https://github.com/n1trux/awesome-sysadmin/pull/123
- [x] copy https://github.com/n1trux/awesome-sysadmin#ticketing-systems
  - [x] remove section from awesome-sysadmin https://github.com/n1trux/awesome-sysadmin/pull/122
- [x] copy https://github.com/n1trux/awesome-sysadmin#xmpp
  - [x] remove section from awesome-sysadmin - https://github.com/n1trux/awesome-sysadmin/pull/138
- [x] copy https://github.com/n1trux/awesome-sysadmin#webmail
  - [x] remove section from awesome-sysadmin
- [x] copy https://github.com/n1trux/awesome-sysadmin#wiki-software
  - [ ] split file storage and synchronization section in subsections
  - [x] remove section from awesome-sysadmin
- [x] copy https://github.com/n1trux/awesome-sysadmin#cloud-storage
  - [x] remove section from awesome-sysadmin
- [x] ~~copy https://github.com/n1trux/awesome-sysadmin#code-review~~
  - [x] ~~remove section from awesome-sysadmin~~
- [x] copy https://github.com/n1trux/awesome-sysadmin#collaborative-software
  - [x] remove section from awesome-sysadmin https://github.com/n1trux/awesome-sysadmin/pull/301
- [x] copy https://github.com/n1trux/awesome-sysadmin#continuous-integration--continuous-deployment to awesom-sysadmin https://github.com/n1trux/awesome-sysadmin/pull/302
  - [x] remove section from awesome-selfhosted https://github.com/Kickball/awesome-selfhosted/pull/1646

---

Delegate and link to awesome-sysadmin:
- [x] ~~link to https://github.com/n1trux/awesome-sysadmin#control-panels~~
- [x] link to https://github.com/n1trux/awesome-sysadmin#distributed-filesystems
- [x] link to https://github.com/n1trux/awesome-sysadmin#dns
- [x] link to https://github.com/n1trux/awesome-sysadmin#identity-management
- [x] link to https://github.com/n1trux/awesome-sysadmin#it-asset-management
- [x] ~~link to https://github.com/n1trux/awesome-sysadmin#mail-servers~~
- [x] link to https://github.com/n1trux/awesome-sysadmin#monitoring - https://github.com/n1trux/awesome-sysadmin/pull/139 https://github.com/Kickball/awesome-selfhosted/pull/477
- [x] link to https://github.com/n1trux/awesome-sysadmin#web
- [x] ~~link to https://github.com/n1trux/awesome-sysadmin#version-control~~ let's keep it in a-selfhosted
- [ ] link to https://github.com/n1trux/awesome-sysadmin#status-pages
- [x] link to https://github.com/n1trux/awesome-sysadmin#vpn
- [x] ~~link to https://github.com/n1trux/awesome-sysadmin#rdbms~~ no existing section in selfhosted
- [x] send patches to awesome-sysadmin for software currently in these sections on awesome-selfhosted
- [x] remove above sections from awesome-selfhosted

---

Network and computer systems management software would live in awesome-sysadmin, while we keep communication systems and non-IT-related services and applications here. I'm still unsure about Mail Servers and Web Servers. Maybe this could be an exception and be present in both lists (they are important for both). Not sure about Analytics either.

@n1trux would this be ok? Everything here can be discussed

**Comment by n1trux** [comment]
:+1:

But I'd really like awesome-selfhosted to be curated more. Currently it's a really long list with software which isn't particularily awesome or even finished at times.

**Comment by Kickball** [comment]
To pick this back up.

I agree with @n1trux that code review, continuous integration and continuous deployment should stay in awesome-sysadmin. However I feel that collaborative software better fits in awesome-selfhosted.

We still need to add in a few links on awesome-selfhosted to awesome-sysadmin, and I can start work on them once I hear back from @nodiscc and @n1trux.

**Comment by nodiscc** [comment]
> I feel that collaborative software better fits in awesome-selfhosted.

This is right and there's a TODO entry for this in the list above.

> copy https://github.com/n1trux/awesome-sysadmin#collaborative-software
>     remove section from awesome-sysadmin

------------------------

>We still need to add in a few links on awesome-selfhosted to awesome-sysadmin, and I can start work on them once I hear back from @nodiscc and @n1trux.

I think you can start right away, the way I used to work on this is (to move entries from here to aw-sys):

1. Copy entries from one of our sections, edit awesome-sysadmin in my own fork to add them there, submit a Pull Request to https://github.com/n1trux/awesome-sysadmin requesting to merge the changes (mention https://github.com/Kickball/awesome-selfhosted/issues/127 in the PR comments to keep track of this work here).
2. Submit a Pull Request here to remove a section (replace by a link to the awesome-sysadmin section), mentioning in the comments that the PR should not be merged before the patch to awesome-sysadmin has been approved (with a link to the PR).
3. Once @n1trux merges our PR, merge the one in this repo.

To move entries the other way (from awesome-sysadmin to awesome-selfhosted), do it in reverse order (copy entries here, submit a Pull Request, merge it, submit a Pull Request to awesome-sysadmin to replace their section with a link to aweseome-selfhosted)

-----------------------------------

Note that the TODO list is incomplete, for example for

>  link to https://github.com/n1trux/awesome-sysadmin#identity-management 

we actually want to move entries from https://github.com/Kickball/awesome-selfhosted#federated-identityauthentication to https://github.com/n1trux/awesome-sysadmin#identity-management following the process described above.

**Comment by n1trux** [comment]
@Kickball: @nodiscc is right,

>I think you can start right away

**Comment by nodiscc** [comment]
commit https://github.com/Kickball/awesome-selfhosted/commit/a21ce6a8fc4d48b1fe1030600715da401e68a07c fixes the last remaining items from this issue. I have birefly check both lists and it appears there are no duplicates anymore, at least no overlapping sections.

> Aug 3, 2015 

feelsgoodman
