### ISSUE TITLE
Update Github project description

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#128]
I thought we could update the Github project description following the current one:

> Selfhosting is the process of locally hosting and managing applications instead of renting from SaaS providers. This is a list of Free Software network services and web applications which can be hosted locally. 

or just the second part. @Kickball I don't have necessary permissions to edit the description

**Comment by Kickball** [comment]
I've gone ahead and changed the description of the project to what you suggested. I don't think it is possible for me to give you permission to edit the description, however if it is please tell me how.
