### ISSUE TITLE
Ombi

### ISSUE THREAD

**Issue by didyouexpectthat** [Kickball/awesome-selfhosted#1286]
[Ombi](https://github.com/tidusjar/Ombi): a content request system for Plex/Emby, connecting to SickRage, CouchPotato, Sonarr, with a growing feature set.  
[Demo](https://camo.githubusercontent.com/c2313b908e0eb6571ba73ed5bc1060efbbadf0fc/687474703a2f2f692e696d6775722e636f6d2f4e6e314277414d2e676966) [Source Code](https://github.com/tidusjar/Ombi) GPL-2.0, English, French, Danish, German, Italian, Spanish, Dutch

**Comment by nodiscc** [comment]
https://github.com/Kickball/awesome-selfhosted/pull/1546
