### ISSUE TITLE
Ensure all software has license

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#13]
We need to ensure that all software has their license attached, in the format:

Software Name - Brief Description (Extra Software Links) - License

**Comment by Kovah** [comment]
I'm on it. ;)

**Comment by nodiscc** [comment]
@Kovah's work rebased in #34
Software that doesn't have license not language tags can be found with ``egrep -v "\`" README.md``

**Comment by jungle-boogie** [comment]
Hello,

I'm updating many that don't have a license listed in the readme, but not all projects list what license they're using, so I've contacted a few to ask for information on it.

thanks,
sean

**Comment by nodiscc** [comment]
Closing in favor of https://github.com/Kickball/awesome-selfhosted/issues/471

`make missinglicenselanguage` may help in the future.
