### ISSUE TITLE
Free as in Freedom or Free Beer?

### ISSUE THREAD

**Issue by InfiniteCoder** [Kickball/awesome-selfhosted#1304]
My guess is that this list is only for "Free as in Freedom" softwares, and not for "Free Beer" softwares. At least the Wikipedia page that this repo points to says 

> Free software is a matter of liberty, not price

But I feel this should be made explicit in either or both the repo description, and the starting of the list.

Eitherway, great work making this list! Here's a (🆓) 🍺 for you 😛

**Comment by nodiscc** [comment]
What do you suggest?

The linked wikipedia page clearly states:

> https://en.wikipedia.org/wiki/Free_software#Definition_and_the_Four_Freedoms
> [...]software is free software if people who receive a copy of the software have the following four freedoms.[...]

>    * The freedom to run the program for any purpose.
>    * The freedom to study how the program works, and change it to make it do what you wish.
>    * The freedom to redistribute and make copies so you can help your neighbor.
>    * The freedom to improve the program, and release your improvements (and modified versions in general) to the public, so that the whole community benefits.

**Comment by InfiniteCoder** [comment]
@nodiscc Maybe also add that link in the repo description at top?  That link could be added to the phrase "Free software" in the description. Or maybe just add "as in Freedom" in paranthesis? Just a suggestion.

**Comment by nodiscc** [comment]
> Maybe also add that link in the repo description at top

The first paragraph in the file already links to it:

----------------------------------------------------------

https://github.com/Kickball/awesome-selfhosted/blob/master/README.md

> # Awesome-Selfhosted

> Selfhosting is the process of locally hosting and managing applications instead of renting from SaaS providers.

> This is a list of [Free](https://en.wikipedia.org/wiki/Free_software) Software [network services](https://en.wikipedia.org/wiki/Network_service) and [web applications](https://en.wikipedia.org/wiki/Web_application) which can be hosted locally. Non-Free software is listed on the [Non-Free](non-free.md) page.

> See [Contributing](.github/CONTRIBUTING.md).
----------------------

CONTRIBUTING.md also does link to it. 

If you mean the Github "repository description" setting, we can't put markdown links in there (just tested on https://github.com/nodiscc/dropbin, see for yourself), and adding the full wikipedia URL would look really bad. (by the way only @Kickball has edit privileges on this setting.)

The repo description uses capitalized words Free Software, so it's less ambiguous. Readers are also supposed to you know, read the file, follow links,... :) But yeah I agree that Free is an unfortunate choice for an english word. Around here we say "Logiciel libre" ▒░▓ 🍺 🍺 🍺 :beer: :beer: < -- non-Free beer for you

Closing for now, feel free to reopen.
