### ISSUE TITLE
Contract (/Compliance) Management Systems?

### ISSUE THREAD

**Issue by terraboss** [Kickball/awesome-selfhosted#1313]
Does someone know any self-hosted solutions? 

Best

**Comment by nodiscc** [comment]
@terraboss It would help if you described what features you are looking for/what does it do/is it just a document organizer? All I could find is https://en.wikipedia.org/wiki/Contract_management_software and https://www.reddit.com/r/selfhosted/search?q=contract&restrict_sr=on&sort=relevance&t=all. Someone suggested Mayan EDMS. Do you have examples of similar software?

**Comment by nodiscc** [comment]
Closing after 1+ month of inactivity.
