### ISSUE TITLE
Crushpaper seems dead

### ISSUE THREAD

**Issue by DBX12** [Kickball/awesome-selfhosted#1327]
The site https://www.crushpaper.com/ is not loading. Does this happen to other as well or is it only me?

If there are a few people confirming the page is down, I vote for removing the link from the section *Misc/Other*

**Comment by nodiscc** [comment]
@DBX12 thanks for noticing. Indeed their website is down and the project looks abandoned. Last commit was 3 years ago. Can you send a Pull Request to remove the crushpaper entry?

**Comment by DBX12** [comment]
Thx @prahaladbelavadi for providing the PR.
