### ISSUE TITLE
Chyrp Lite Fork

### ISSUE THREAD

**Issue by jaywilliams** [Kickball/awesome-selfhosted#1337]
[Chyrp](https://github.com/chyrp/chyrp) hasn't been updated in two years, however a fork named [Chyrp Lite](http://chyrplite.net) has continued to develop the application and fix bugs.

Project Page: http://chyrplite.net
Source Code: https://github.com/xenocrat/chyrp-lite

Should the link to Chyrp be renamed to Chyrp Lite or should both be listed?

**Comment by nodiscc** [comment]
Chyrp was quite good at the time I used it. 

> Should the link to Chyrp be renamed to Chyrp Lite or should both be listed?

You can update the old link and point it to Chyrp Lite since the former is not maintained anymore.

**Comment by jaywilliams** [comment]
Pull request created. I updated the license information as well, as it uses BSD rather than MIT.

**Comment by nodiscc** [comment]
Fixed in https://github.com/Kickball/awesome-selfhosted/pull/1346
