### ISSUE TITLE
Add awesome-public-datasets to external links

### ISSUE THREAD

**Issue by rory** [Kickball/awesome-selfhosted#1352]
OpenStreetMap is described as "GPL-2.0 Ruby", which isn't very helpful. The website & editing API is written in ruby and is GPL, but basically no-one needs that. It's more accurate to talk of the data, which is ODbL licenced, and is available in (OSM's custom) XML & PBF formats.

**Comment by evaryont** [comment]
You're right, it's hard to describe OpenStreetMap as a self-hosted project. It's all about the data and individual software components. We could instead list Nominatium, iD Editor, etc as individual entries in the list.

A comparison: do we list Wikipedia on here? No, but we do list the major software component powering Wikipedia, MediaWiki. There isn't a single piece of software to point to, to say to others "run this to make your own OSM!".

**Comment by rory** [comment]
For WIkipedia, a lot of people use MediaWiki for their own wikis. Very very few people need a local OSM editing website. Wikipedia is mostly consumed via wikipedia.org. OSM data is consumed in many pieces of software. If you want to make something (self hosted) which uses map data, then you'd benefit from knowing about OSM, but I see your point about this being a list of *hosting*.

**Comment by nodiscc** [comment]
The OSM dataset is listed in https://github.com/awesomedata/awesome-public-datasets. What do you think about linking to this list from https://github.com/Kickball/awesome-selfhosted#external-links ?

**Comment by rory** [comment]
That probably makes more sense then

**Comment by nodiscc** [comment]
@rory do you want to send a pull request?
