### ISSUE TITLE
Adding Pleroma Social?

### ISSUE THREAD

**Issue by mitchellurgero** [Kickball/awesome-selfhosted#1366]
Can we add Pleroma to the Social network list?

https://pleroma.social.

A Mastodon / GNUSocial compatible server written in Elixir. Extremely light footprint. Can run on a Raspberry Pi.

**Comment by nodiscc** [comment]
https://github.com/Kickball/awesome-selfhosted/commit/edf870119e59194f7ae415e0915d2269c6231cca

**Comment by Kickball** [comment]
Related PR: #1368.
