### ISSUE TITLE
Add Poste to email server list

### ISSUE THREAD

**Issue by theel0ja** [Kickball/awesome-selfhosted#1370]
Link to their website: https://poste.io/

**Comment by disk0x** [comment]
A problem I see with that, is that I can't find the Dockerfile required to reproduce and modify the image for poste.io. 

I might have missed it of course.

**Comment by Kickball** [comment]
Echoing @disk0x's points, I can't find the source code for this project on the website linked, so closing the issue.

@theel0ja please let us know if the source code is open source and we can re-open the issue.
