### ISSUE TITLE
bepasty

### ISSUE THREAD

**Issue by Marwe** [Kickball/awesome-selfhosted#1375]
for the category: Single-click/drag-n-drop upload

- [bepasty](http://bepasty-server.readthedocs.org/en/latest/) - bepasty is like a pastebin for all kinds of files ([Source Code](https://github.com/bepasty/bepasty-server)) `BSD 2-Clause "Simplified" License` `Python`.

**Comment by nodiscc** [comment]
https://github.com/Kickball/awesome-selfhosted/pull/1546
