### ISSUE TITLE
Pi-hole

### ISSUE THREAD

**Issue by mzac** [Kickball/awesome-selfhosted#1386]
To be added to the category DNS

- Pi-Hole - A BLACK HOLE FOR INTERNET ADVERTISEMENTS
- https://pi-hole.net/

**Comment by nodiscc** [comment]
Already listed at https://github.com/n1trux/awesome-sysadmin#control-panels (https://github.com/n1trux/awesome-sysadmin/pull/258) - we're trying to reduce overlap between the 2 lists https://github.com/Kickball/awesome-selfhosted/issues/127 and it's better suited to awesome-sysadmin than here, so closing.
