### ISSUE TITLE
LDAP Server?

### ISSUE THREAD

**Issue by benyanke** [Kickball/awesome-selfhosted#1387]
I just took over maintaining a lightweight LDAP server ([glauth](https://github.com/glauth/glauth)), and I'm wondering if it would be appropriate on this list? I noticed you don't have any LDAP servers, but it might be of interest to those who are selfhosting things.

It's very lightweight, so well suited to small homelabs (at minimum, a static binary + a single config file).

**Comment by benyanke** [comment]
Any thoughts on this?

**Comment by nodiscc** [comment]
@benyanke You can find LDAP servers listed here: https://github.com/n1trux/awesome-sysadmin#identity-management.

There is a link to this section in https://github.com/Kickball/awesome-selfhosted#federated-identityauthentication

I suggest you take a look at their contribution guidelines and send a Pull Request their way. awesome-sysadmin is slightly more restrictive than awesome-selfhosted, the software must be production ready and IIRC they ask you to write a short paragraph on how awesome it is/key features/use cases.
