### ISSUE TITLE
talkyard

### ISSUE THREAD

**Issue by denji** [Kickball/awesome-selfhosted#1390]
* https://github.com/debiki/talkyard

Open source StackOverflow, Slack, Discourse, Reddit, Disqus hybrid — for your online community.

https://github.com/debiki/talkyard#screenshots

**Comment by Kickball** [comment]
#1400 raised to add Talkyard, pending [#27](https://github.com/debiki/talkyard/issues/27) on the Talkyard project to understand whether it is self-hostable without docker.

**Comment by nodiscc** [comment]
Merged https://github.com/Kickball/awesome-selfhosted/pull/1400
