### ISSUE TITLE
Add a programming language tag?

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#14]
Should we also reference the main source code language for each project? eg. `Python` or `PHP`
It helps knowing if the app just needs a LAMP stack to run, or a whole another setup like python-wsgi, nodejs..

By the way, thanks for starting this project!

**Comment by Kovah** [comment]
I would suggest adding a `(FR)` or `(NL)` two-letter language code if the software is language-specific.
Example:

* [PluXml](http://www.pluxml.org/) (FR) - XML-based blog/CMS platform - `GNU-GPL`

**Comment by nodiscc** [comment]
@Kovah I was suggesting to add the software's _programming_ language

**Comment by Kovah** [comment]
Whoops, sorry!

**Comment by Kickball** [comment]
We can look at doing this and in the same way @Kovah suggested we do a language tag:

* [PluXml](http://www.pluxml.org/) (PHP) - XML-based blog/CMS platform - `GNU-GPL`

**Comment by nodiscc** [comment]
Ok. I suggest we only include the project's _main_ language, in cases where it uses several languages.

**Comment by nodiscc** [comment]
Added to the CONTRIBUTING section.
