### ISSUE TITLE
Update Libravatar (Federated Identity/Authentication)

### ISSUE THREAD

**Issue by Kickball** [Kickball/awesome-selfhosted#140]
We need to add:

Libravatar - https://www.libravatar.org/

Libravatar is a service which delivers your avatar (profile picture) to other websites.

AGPLv3 License.

Demo: https://www.libravatar.org/

Source Code: https://code.launchpad.net/libravatar

Primary Programming Language: Django (I think)

**Comment by nodiscc** [comment]
Already at https://github.com/Kickball/awesome-selfhosted#federated-identityauthentication but missing info

**Comment by Kickball** [comment]
#369 updates Libravatar with relevant details.
