### ISSUE TITLE
Git Annex Github URL Incorrect

### ISSUE THREAD

**Issue by Kickball** [Kickball/awesome-selfhosted#1401]
https://github.com/joeyh/git-annex linked in the Git Annex item is no longer accessible.

**Comment by evaryont** [comment]
Indeed, I believe he deleted the Github repository due to the Microsoft acquisition.

https://git-annex.branchable.com/install/fromsource/ documents how to build from source, but there isn't an obvious link to browse the source code via a web browser. Is that good enough?
