### ISSUE TITLE
possible License infringement

### ISSUE THREAD

**Issue by DJCrashdummy** [Kickball/awesome-selfhosted#1440]
i stumbled accidentally across [_"Awesome Self Hosted"_](https://selfhosted.libhunt.com/) which looks pretty cool, but after a short time i realized that it is pretty sure based on this project and its information, structure, etc.

so far so good, but to proof my assumption i looked around for some references and the only thing i found was this statement at the bottom of the page:
> [...] The collection of libraries and resources is based on the _Awesome Self Hosted List_ and direct contributions here. [...]

- without any link or further reference... IMHO this is not an appropriate attribution!
- beside that it looks like they intend to cause a mix-up because of the similar names, no links and no further explanation.
- and as icing on the cake the footer closes with the following statement:
  > Awesome Self Hosted is part of the [LibHunt](http://www.libhunt.com/) network. [Terms](https://selfhosted.libhunt.com/terms). [Privacy Policy](https://selfhosted.libhunt.com/privacy).
[(CC) BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/)

  IANAL but i guess because of the here used [Creative Commons Attribution-ShareAlike 3.0 Unported](https://github.com/Kickball/awesome-selfhosted/blob/master/LICENSE), the license can even not be changed to [(CC) BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/)...?

**Comment by nodiscc** [comment]
See also https://github.com/Kickball/awesome-selfhosted/issues/465#issuecomment-227962091

------------------------

> without any link or further reference... IMHO this is not an appropriate attribution!

https://selfhosted.libhunt.com/terms says:

>License
>ATTRIBUTION: The original contributors of the lists with services, libraries and tools that "Awesome Self Hosted @ LibHunt" is based on could be found here: https://github.com/Kickball/awesome-selfhosted. A number of changes have been made after the initial use of the original list. For example: extending the list, adding additional metadata, reordering the lists, providing a comprehensive UI and search tools and more. 

----------------------------

> IANAL but i guess because of the here used Creative Commons Attribution-ShareAlike 3.0 Unported, the license can even not be changed to (CC) BY-SA 4.0...?

https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses/ says:

> Your contributions to adaptations of BY-SA 3.0 materials may only be licensed under:
>    BY-SA 3.0, or a later version of the BY-SA license.
> ...

--------------------------------------------

> beside that it looks like they intend to cause a mix-up because of the similar names, no links and no further explanation.

Yes they are not willing to link to us in a more visible manner, and are also name-squatting to increase the visibility in search engines. I don't agree with that, but again there is nothing here that infringes the license. https://creativecommons.org/licenses/by-sa/4.0/legalcode. The upside is that data that they have added to their copy of the list must stay CC-BY-SA-4.0 or later.

Feel free to close if it answers your questions.
