### ISSUE TITLE
"Note-taking and Editors" vs. "Pastebins"

### ISSUE THREAD

**Issue by DJCrashdummy** [Kickball/awesome-selfhosted#1447]
please can somebody be so kind and explain the differences between [*Note-taking and Editors*](https://github.com/Kickball/awesome-selfhosted#note-taking-and-editors) and [*Pastebins*](https://github.com/Kickball/awesome-selfhosted#pastebins) to me... or at least what should be the differences, because i'm pretty sure these 2 sections are partly mixed-up. :confused:

**Comment by nodiscc** [comment]
* Pastebins [[w]](https://en.wikipedia.org/wiki/Pastebin): **write once**, read many text editors. Mostly used for temporary text storage (ie. paste a text file for demonstration/review purposes and forget about it). A paste typically has a fixed URL attached to it (permalink, eg https://pastebin.com/v5u9yYrk) and cannot be changed. It may have additional features like cloning/editing a paste, setting lifetime of pastes, highlighting... but it's mainly used to copy-paste text between computers.

 * Note taking and editors: Used as permanent storage and editing tools for personal notes. May have additional features like notes organization, markdown/rst/... syntax support/hightlighting, attaching files... But basically they are not read-only, and serve a different purpose.

There could be a subcategory named _Pads_, which are collaborative real-time text editors (the most well known is probably [Etherpad](https://en.wikipedia.org/wiki/Etherpad)); and another category for purely drawing/_graphic editors_ like _draw.io_

>i'm pretty sure these 2 sections are partly mixed-up. confused

I had a quick look and nothing seems out fo place to me. Which specific entries? Or does it answer your question?

**Comment by Kickball** [comment]
Totally agree with @nodiscc's description of the sections.

A *Pads* section would cover the apps that fall into a grey area like Cryptpad and some others, but I don't needs to be a priority.

@DJCrashdummy, I'm going to close the issue as last activity is from end of June, it can be reopened as needed.
