### ISSUE TITLE
Ensure all licenses are in the license section

### ISSUE THREAD

**Issue by Kickball** [Kickball/awesome-selfhosted#145]
There are a few licenses which software on our list uses but which isn't in our licensing [section](https://github.com/Kickball/awesome-selfhosted#list-of-licenses). We will need to add these licenses.

**Comment by n8225** [comment]
It looks like Kriss Feed is the only entry left without a license.  I opened an issue there a week ago and from what I can tell the author has no intention of licenseing it other than Copyleft (ɔ).  From what I have read copyleft isnt really a license.  @nodiscc what are your thoughts on this?

**Comment by nodiscc** [comment]
Let's wait for a conclusion to https://github.com/tontof/kriss_feed/issues/375

**Comment by nodiscc** [comment]
https://github.com/tontof/kriss_feed/issues/375 CC0

**Comment by nodiscc** [comment]
Fixed in https://github.com/Kickball/awesome-selfhosted/issues/780
