### ISSUE TITLE
add disposable-mailbox

### ISSUE THREAD

**Issue by synox** [Kickball/awesome-selfhosted#1451]
I would like to add https://github.com/synox/disposable-mailbox

See PR #1448 

+- [Disposable Mailbox](https://github.com/synox/disposable-mailbox) - Simple disposable mailbox web app based on a catch-all IMAP mailbox.  `GPL-3.0` `PHP`

**Comment by Chouchen** [comment]
It's missing the demo link.

**Comment by synox** [comment]
I added the demo link

**Comment by nodiscc** [comment]
Merged https://github.com/Kickball/awesome-selfhosted/pull/1448
