### ISSUE TITLE
Add HRConvert2

### ISSUE THREAD

**Issue by zelon88** [Kickball/awesome-selfhosted#1466]
Hi there! 

My name is Justin. I already have an application on the awesome-selfhosted list under Groupware called HRCloud2.

I would like to propose that HRConvert2 be added to the list. It is a file converter based on the internal converter code of my other project. This is basically a stripped down HRCloud2 with the user auth, WordPress integration, App Launcher, log viewer, and Cloud operations removed. This leaves pretty much just the converter with a new cookie-less token based auth mechanism to keep user files separate. So where HRC2 requires user accounts before a user can upload and convert files, HRConvert2 will allow anyone to upload and convert files. 

It is most similar to Convertio or www[dot]online-convert[dot]com, but you host it yourself.

It currently supports 59x file formats, and can convert office documents, images, audio, video, vector drawings, 3D models, presentation files, spreadsheets, archives, and disk images. It even OCR's multi-page PDF's and images into documents.

Not sure where it should go but I'm open to suggestions.

CODE:
https://github.com/zelon88/HRConvert2

DEMO:
https://www.honestrepair.net/index.php/convert/

**Comment by nodiscc** [comment]
https://github.com/Kickball/awesome-selfhosted#groupware

**Comment by nodiscc** [comment]
My bad, _"This is basically a stripped down HRCloud2"_ mad me think it retained most of the features of HRCloud2, while in fact it only retains the video conversion feature. I think _Automation_ category would be more appropriate. Thanks for pointing it out

**Comment by Kickball** [comment]
Added in #1571.
