### ISSUE TITLE
Is cloudron still awesome?

### ISSUE THREAD

**Issue by n1trux** [Kickball/awesome-selfhosted#1468]
Seems to be [the case that you have to pay 15$/month](https://cloudron.io/pricing.html) if you have more than 5 users or 2 apps:

>Free: 0 $/mo, 2 Apps, 5 Cloudron Users, Automatic Updates, Email Solution

>Basic: 15 $/mo, 20 Apps, 30 Cloudron Users, Automatic Updates, Email Solution, Priority Support

See also the discussion on my repo: n1trux/awesome-sysadmin#274

Does that still qualify as awesome for awesome-selfhosted, even though it's crippled in the GPL version? Or should we add a flag "free for <5 users" to the list?

**Comment by nodiscc** [comment]
@n1trux I have been following the discussion in your repo and yes the (severe) crippling of the GPL version is not something I like. The limitation is entirely artificial and includes removed features AND limitations on the number of apps AND users.

I am thinking about rewriting the description to something like _Effortlessly self-host 2 web apps on your server for max. 5 users_. Or move it to non-free.md with a mention that a crippled Free version exists.

Thanks for getting in touch
Any advice is welcome

**Comment by n1trux** [comment]
>Effortlessly self-host 2 web apps on your server for max. 5 users

Snarky, funny, I like it but I guess neither the devs nor the FOSS community would be particularly happy about that :'D

>move it to non-free.md with a mention that a crippled Free version exists.

Not the worst idea, tbh!

The premise of Cloudron is pretty cool, but it's not really Free as in Freedom as you had to basically fork the thing and completely replace all of the "App Store" code with your own to run your own "repository".

I don't really think that if you have to use the CLI if you want to use the free version, Cloudron offers something more than [Portainer](https://www.portainer.io/) or other similar control panel softwares.

>Any advice is welcome

I'd propose this: move to `non-free.md` and add Portainer to the "regular" list as alternative? Maybe wait for more input from other contributors?

>Thanks for getting in touch

Thanks for answering!

**Comment by nodiscc** [comment]
The fairest thing to do is probably to add the `⚠` symbol for the cloudron entry to signify the reliance on their App Store (and other services). Maybe add `Free Software offering has strong limitations` to the description.

Other projects have limitations for their non-professional/non-SaaS editions. I still think cloudron's limitations are heavy-handed but we cannot blame them for trying to find a sustainable model. (2 applications might be enough for many people. if data is easily exportable and it doesn't actively lock-in/hamper users trying to move to alternatives, then I see no problem)

**Comment by Kickball** [comment]
I don't think we can consider it free fully open sourced software with such limitations on it, I would suggest that we move Cloudron to non-free.md and add Portainer to the standard readme.md (⚠ though as it has a docker dependancy).

What are your thoughts @nodiscc?

**Comment by SemperFu** [comment]
I agree with @Kickball I don't consider this to be awesome. Having a virtualization/container section might make sense showing proxmox, docker+portainer, or rancheros + rancher2.0

**Comment by nodiscc** [comment]
> move Cloudron to non-free.md

I am fine with that. Maybe mention that it is "open-core".

> add Portainer

I think we should try to add it to https://github.com/n1trux/awesome-sysadmin#software-containers first (alongside Docker Compose and Swarm)

> showing proxmox

Proxmox ( :heart:   ) is already listed at https://github.com/n1trux/awesome-sysadmin#virtualization

**Comment by Kickball** [comment]
#1508 raised for the cloudron move.

**Comment by SemperFu** [comment]
> > add Portainer
> 
> I think we should try to add it to https://github.com/n1trux/awesome-sysadmin#software-containers first (alongside Docker Compose and Swarm)

I will put in a request on awesome-sysadmin for portainer, & rancher tonight/tomorrow.

**Comment by nodiscc** [comment]
Fixed in https://github.com/Kickball/awesome-selfhosted/pull/1508

**Comment by SemperFu** [comment]
Portainer PR added
https://github.com/n1trux/awesome-sysadmin/pull/281
