### ISSUE TITLE
[Question] Why non-free.md?

### ISSUE THREAD

**Issue by Retia-Adolf** [Kickball/awesome-selfhosted#1483]
In [non-free.md](https://github.com/Kickball/awesome-selfhosted/blob/master/non-free.md), there written:

> Software listed here does not allow you to run it for any purpose

What does it mean? Is it refer to "any purpose" that involved " study, modify or distribute the source code" ?

Also, there's an Unlicensed software listed, but it's [GPL-compatible](https://www.gnu.org/licenses/license-list.html#Unlicense). Is there anyone could explain to me? Thank you!

> Gazelle - Gazelle is a web framework geared towards private BitTorrent trackers. Although naturally focusing on music, it can be modified for most needs. unlicensed

**Comment by SemperFu** [comment]
Most likely because it is only for non commercial unlike GPL.

> Software under the GPL may be run for all purposes, including commercial purposes

> This Software is distributed pursuant to the terms and conditions
> of this License and is distributed free of charge **FOR NONCOMMERCIAL PURPOSES
> ONLY**.  THE USE, DISTRIBUTION AND/OR MODIFICATION OF THIS SOFTWARE FOR
> COMMERCIAL PURPOSES IS EXPRESSLY PROHIBITED BY INTERNATIONAL LAWS AND TREATIES
>

**Comment by SemperFu** [comment]
@nodiscc can this be closed?

**Comment by Retia-Adolf** [comment]
@SemperFu Thx for answering. So I guess the Gazelle is not licensed under the `Unlicense`, instead it's a freeware for non-commercial purpose.

And the first sentence in `non-free.md` is actually means "Software listed here does not allow you to run it for any purpose, (**including but not limited to**) study, modify or distribute the source code. ", right?

**Comment by nodiscc** [comment]
- The "unlicensed" tag on Gazelle is incorrect since the license can be found [here](https://github.com/WhatCD/Gazelle/blob/63b337026d49b5cf63ce4be20fdabdc880112fa3/docs/COPYING.txt)
- Gazelle looks abandoned since 2016, it might be time to remove it from the list
- The first sentence means that if the license limits the purposes for which you are allowed to run the software, it is not Free Software.
