### ISSUE TITLE
Please move CryptPad to Office-Suites

### ISSUE THREAD

**Issue by polx** [Kickball/awesome-selfhosted#1506]
Please move CryptPad to office-suites.
The use as paste-bin is indeed correct, but that is just a small fraction of the functions.
Pull-request [1505](https://github.com/Kickball/awesome-selfhosted/pull/1505) has been opened for this.
thanks
paul

**Comment by polx** [comment]
This is my first pull-request to this site... thanks for the patience if the protocol needs adjustment.
For some reasons, I was unable to add a help-requested label.
paul

**Comment by Kickball** [comment]
Related #1505.
