### ISSUE TITLE
Add Jekyll to Blogging Platforms and CMS

### ISSUE THREAD

**Issue by neo22s** [Kickball/awesome-selfhosted#152]
http://jekyllrb.com/

**Comment by nodiscc** [comment]
We don't list static site generators, please see https://github.com/Kickball/awesome-selfhosted/issues/72, https://github.com/Kickball/awesome-selfhosted/issues/66, https://github.com/Kickball/awesome-selfhosted/issues/41. Can you remove this entry?

**Comment by neo22s** [comment]
sorry! good lord we all like the same ;) thanks

**Comment by nodiscc** [comment]
Yep Jekyll comes up often :) Thank you
