### ISSUE TITLE
Link doesn't work

### ISSUE THREAD

**Issue by MrAgame13** [Kickball/awesome-selfhosted#1530]
https://github.com/Kickball/awesome-selfhosted#games

Link of the "0hh1" repository doesn't work. The page is not found.

**Comment by nodiscc** [comment]
It's being removed as part of https://github.com/Kickball/awesome-selfhosted/pull/1517/files

**Comment by himankpathak** [comment]
@MrAgame13 this issue can be closed now as its resolved.
