### ISSUE TITLE
Add Anuko to misc/other

### ISSUE THREAD

**Issue by Andyyyyy94** [Kickball/awesome-selfhosted#1534]
Hi folks,

first things first: I love this awesome list and want to contribute to it.

Anuko is a time tracker, as Kimai is, which is already listed at misc/other.
[https://www.anuko.com/time_tracker/index.htm](https://www.anuko.com/time_tracker/index.htm)

Would appreciate feedback.

**Comment by Kickball** [comment]
This looks fine to me, it looks as though the software - while restricted online - is available without restricted when [selfhosted](https://www.anuko.com/time_tracker/download.htm). Additionally [the license](https://github.com/anuko/timetracker/blob/master/license.txt) is not restrictive.

Please raise a pull request to add this to the awesome list. Let me know if you need any help with it.

**Comment by Andyyyyy94** [comment]
https://github.com/Kickball/awesome-selfhosted/pull/1543
