### ISSUE TITLE
Please remove Tellform

### ISSUE THREAD

**Issue by seidler2547** [Kickball/awesome-selfhosted#1570]
Tellform seems dead, at least for self-hosting. There are various issues that indicate that running via [docker](https://github.com/tellform/tellform/issues/308) [doesn't](https://github.com/tellform/tellform/issues/307) [work](https://github.com/tellform/tellform/issues/277), and that it's [not self-contained](https://github.com/tellform/tellform/issues/310) (i.e. it needs external servers to work), and that some of the [required servers](https://github.com/tellform/tellform/issues/307) are down or not working as they should.

And after some hours of trying to get it to work at all, I can confirm that it seems impossible right now.

**Comment by Kickball** [comment]
#1579 has been raised to remove this, I agree that several issues (check the issues list for more info) have been raised about several of the deployment platforms and the core functionality of the application itself not working, showing that while it was recently updated (Oct 24th), it isn't functioning as it should be.

@James9074 & @whitef0x0 can submit a new PR to re-add it if it is picked back up.

**Comment by wodka** [comment]
Hi :)

It has been picked up as https://github.com/ohmyform/ohmyform

**Comment by petrk94** [comment]
@wodka thanks, looks interesting, I will try it whether its working

**Comment by karser** [comment]
I launched and played with ohmyform. It's not production ready but has great potential and definitely worth including into this list.
