### ISSUE TITLE
Add LinuxGSM

### ISSUE THREAD

**Issue by dgibbs64** [Kickball/awesome-selfhosted#1590]
I develop [LinuxGSM](https://linuxgsm.com) and was wondering if LinuxGSM is the sort of project that might be appropriate for this list? There are also a few other tools for hosting game servers such as Pterodactyl Panel that might be a good fit for this list as well.

**Comment by nodiscc** [comment]
After quickly reading through these projects homepages I think they would qualify and should be added to the list. I'm redirecting this to https://github.com/Kickball/awesome-selfhosted/issues/1555 where a similar discussion was started some time ago.

**Comment by dgibbs64** [comment]
That's awesome thanks :)
