### ISSUE TITLE
Should ownCloud also have an entry in Groupware?

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#162]
Since ownCloud supports shared calendars/address books (+ CardDAV/CalDAV), should it also have an entry in the Groupware scetion? The current description doesn't mention those features

**Comment by Kickball** [comment]
I think that ownCloud (and any other groupware applications in the File Sharing and Synchronization section) should be moved to groupware. We can do this along side the split of File Sharing and Synchronization (#161).

**Comment by nodiscc** [comment]
> moved to groupware

but owncloud also has file sync (it's main feature).

**Comment by Kickball** [comment]
I have moved it over in 98d1ccc, if you feel it should be on both Groupware and File Sharing and Synchronization  then feel free to revert the commit, or readd it to File Sharing and Synchronization.
