### ISSUE TITLE
Add koken.im

### ISSUE THREAD

**Issue by pandruszkow** [Kickball/awesome-selfhosted#1640]
Koken is a free (as in gratis) image gallery software which can be self-hosted. The licensing is a non-standard (see http://koken.me/eula.html) and the install package is non-redistributable, but it can be used for both commercial and non-commercial uses as long as it's not used `as the basis of a hosted web site publishing service`.

**Comment by worldworm** [comment]
Already listed in non-free.md https://github.com/Kickball/awesome-selfhosted/pull/975
