### ISSUE TITLE
is there a "most popular" or "most friendly"

### ISSUE THREAD

**Issue by magik20** [Kickball/awesome-selfhosted#1657]
while this list is amazing and exhaustive, its incredibly daunting...

any list that narrows down the options (a lot)?

**Comment by n8225** [comment]
You could try https://n8225.github.io/Awesome-Selfhosted-Gen/

Same list but different and maybe a month out of date.

**Comment by nodiscc** [comment]
> narrows down the options

@artiedarrell Based on what criteria should the list be curated/narrowed down?

**Comment by nodiscc** [comment]
No reply, closing.
