### ISSUE TITLE
ipMagnet (File Sharing and Synchronization) Invalid?

### ISSUE THREAD

**Issue by Kickball** [Kickball/awesome-selfhosted#167]
[ipMagnet](https://github.com/cbdevnet/ipmagnet/) is currently part of our File Sharing and Synchronization section, however it does not allow for any sort of file sharing or synchronization. The [demo](http://ipmagnet.services.cbcdn.com/) shows a simple web interface which displays your publicly facing IP address. 

Unless I've missed features this shouldn't be on our list as the same can be achieved by a quick Google Search.

**Comment by nodiscc** [comment]
Confirmed. We should remove it.

**Comment by Kickball** [comment]
Removed in 54db478.
