### ISSUE TITLE
Add Minimum Viable Startpage

### ISSUE THREAD

**Issue by xelarate86** [Kickball/awesome-selfhosted#1671]
[Minimum Viable Startpage](https://github.com/0-Tikaro/minimum-viable-startpage) could fall under the "Personal Dashboards" section.

**Comment by nodiscc** [comment]
@xelarate86 Thank you for the suggestion. However I don't know if we should list simple startpages like this here. There are hundreds of startpages around (examples at https://www.reddit.com/r/startpages) and we try to avoid cluttering the list when there is already a project that keeps track of a particular topic. For startpages I found https://startpages.github.io/ / https://github.com/startpages/startpages.github.io.


Can you submit Minimum Viable Startpage there? Then we can add a link to startpages.github.io at the top of the "Personal Dashboards" section.

**Comment by davidak** [comment]
It's not there. https://github.com/startpages/startpages.github.io/search?q=Viable&unscoped_q=Viable

@nodiscc maybe you can move the issue there if they accept?

**Comment by nodiscc** [comment]
@davidak issues can't be moved across Github projects. If you have interest in doing the things I listed above, please let us know.

Closing as the original reporter did not reply for 5 months
