### ISSUE TITLE
Add Coder

### ISSUE THREAD

**Issue by amirasyraf** [Kickball/awesome-selfhosted#1679]
Online, self-hosted VSCode.

https://github.com/cdr/code-server

**Comment by SuperSandro2000** [comment]
If this gets added it should be noted that it is in early development and has some performance issue IIRC.

**Comment by worldworm** [comment]
Already here. https://github.com/Kickball/awesome-selfhosted/commit/6b5bbc32fc3c4b3761836372bb321f3f881328f6
BUT: The name of the organization has changed, so perhaps it makes sense to correct it. So the redirect is gone and no one else can grab the name and do nonsense.
