### ISSUE TITLE
Remove Keepass

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#169]
Keepass was added in https://github.com/Kickball/awesome-selfhosted/commit/6f15389f97aff2ee4055ae0c1fa8169a2165f628 and does not belong to this list. It's a local, desktop application (see https://github.com/Kickball/awesome-selfhosted/pull/43 for similar case with `passwordstore`). Thanks @dpfaffenbauer for noticing (#168)

**Comment by Kickball** [comment]
Removed in #168.
