### ISSUE TITLE
Add MkDocs

### ISSUE THREAD

**Issue by ventolinmono** [Kickball/awesome-selfhosted#1690]
Add MkDocs to Documentation Generators. MkDocs is project documentation with Markdown. BSD license. https://www.mkdocs.org

**Comment by worldworm** [comment]
Nope, see https://github.com/Kickball/awesome-selfhosted/search?q=mkdocs&type=Issues&utf8=%E2%9C%93

_Originally posted by @nodiscc in https://github.com/Kickball/awesome-selfhosted/issues/911#issuecomment-268283915_

**Comment by nodiscc** [comment]
https://github.com/Kickball/awesome-selfhosted#static-site-generators
