### ISSUE TITLE
92five should be moved to proprietary

### ISSUE THREAD

**Issue by pizzamaker** [Kickball/awesome-selfhosted#172]
CC BY-NC is not a free license, therefore 92five needs to be moved to the nonfree (proprietary) list.

**Comment by nodiscc** [comment]
It seems the situation is worse, it's licensed under `CC BY-ND` https://github.com/chintanbanugaria/92five/blob/master/LICENSE, so definitely non-free.

**Comment by Kickball** [comment]
It doesn't seem that bad. [Summary of license](http://creativecommons.org/licenses/by-nd/4.0/).

**Comment by nodiscc** [comment]
https://creativecommons.org/licenses/by-nd/4.0/

> If you remix, transform, or build upon the material, you may not distribute the modified material. 

https://en.wikipedia.org/wiki/Free_software

> freedom to run the software for any purpose as well as to study, modify, and distribute the original software and the adapted versions

Not judging whether it's good or bad; but that license is non-free.

https://en.wikipedia.org/wiki/Creative_Commons_license#Six_regularly_used_licenses

**Comment by Kickball** [comment]
Alright, I missed that key point. Lets move it to non-free.
