### ISSUE TITLE
Ability to have users rate the self-hosted items

### ISSUE THREAD

**Issue by ikwyl6** [Kickball/awesome-selfhosted#1728]
Not sure if github has this ability but be able to have users rate the items in certain sub-lists so you can see rating levels for each one.

**Comment by nodiscc** [comment]
> Not sure if github has this ability

It doesn't. The list is just a text file, it's not interactive.

It was suggested in https://github.com/Kickball/awesome-selfhosted/issues/1684 that we could show some metrics like the number of Github stars next to each entry

This requires a large refactoring of how the list works - ie. convert the list to yaml/json and let a script grab the stats - see https://github.com/Kickball/awesome-selfhosted/issues/1038). Note that only relying on GH stars somehow penalizes projects that are not on Github.

But, admitting we could implement our own like/stars/rating system, this raises the following questions:

 - who would be allowed to vote/rate?
 - what prevents someone from voting multiple times?

**Comment by ikwyl6** [comment]
Yeah it's not a straight forward answer.. or something that is easily implemented. that's why I was asking about the github ranking system, which would be great, but probably not already in place. It wouldn't really work or it would have un-skewed data unless some kind of authenticated user could rate while logged in. If there was a GH system, you would have to limit ranking/rating to people having github accounts. 

I think showing the number of github stars #1684 wouldn't really show the proper metric we are looking for but would be a temporary start I suppose. It wouldn't really compare how self-hosted-related-01 self-hosted-related-02 is better than one or the other. They could have the same star from the same user.

From https://github.com/Kickball/awesome-selfhosted/issues/1038#issuecomment-452094470
The link to the @n8225 io website seems to make it look a lot nicer than the default README file. That could be used for the layout but how to track all the ratings using that is the big question unless there's a way to do it on the backend of the io site (haven't put any pages on a io site before) using yaml or json like you mentioned.

To answer you above questions:
1) Who would be allowed to vote - if it was me, I would like to keep it to github users. Even if they don't have a github site, we can still rate them (if a github/script/json system was able). If you go from github to another 3rd party website then you would have to keep syncing the GH user with the 3rd party website constantly and doesn't seem efficient.

2) What prevents someone from voting multiple times - would have to be built into the backend of the io or future GH system and compare the GH authenticated user.

**Comment by evaryont** [comment]
Given the complications already pointed out, and the general hassle of managing a server for a project that doesn't have one, I'm not in favor of going that route.

If you want to allow users to rate projects, I'd recommend implementing something yourself. If you do that, we can link it prominently in the README so that people can find it. There are also existing options, like https://alternativeto.net/.

**Comment by nodiscc** [comment]
I wouldn't want this to depend on Github services/authentication. Anyway multiple accounts could be created to vote multiple times. Apparently alternativeto already has to [deal with consntant spam](https://alternativeto.net/faq/what-is-rank-that-applications-are-sorted-by-):

>Rank is our own algorithm for determining how good an app is. It consists of several different parameters. Number of likes is one of the most important parameters but a lot of other factors also comes into play. Unfortunately, spammers try to take advantage of sites like AlternativeTo so we need to keep most of the algorithm logic to ourselves.


The only "easily" implementable way would be to add a "likes" field for each entry, and let people increment that through pull requests. But this would create an unmanageable amount of pull requests to review.

So yes, you would have to design and write something robust yourself. Hosting it is not a problem, making it reliable is hard.

Let's move this discussion to https://github.com/Kickball/awesome-selfhosted/issues/1684, we can always reopen this issue if something specific to voting/ranking comes up. The most important issues related to curation are https://github.com/Kickball/awesome-selfhosted/issues/1038 and https://github.com/Kickball/awesome-selfhosted/issues/1013
