### ISSUE TITLE
Add Encryptr (Password Managers)

### ISSUE THREAD

**Issue by spodkowinski** [Kickball/awesome-selfhosted#173]
https://encryptr.org/
A free, open source password manager, which encrypts or decrypts your data locally on your device. No plain text is ever sent to the server

**Comment by Kickball** [comment]
Is the server self-hosted, or is it only the client you run locally?

**Comment by cfarence** [comment]
@Kickball I was asking the same question when I saw this a month ago. I don't think it can be self hosted. Looks like just the clients can be run locally.

**Comment by spodkowinski** [comment]
The backend service for the client, call Crypton, is on github as well. The installation process is described [here](https://crypton.io/docs/getting-started.html). Afterwards you should be able to point the client to your own address by [editing a file](https://github.com/devgeeks/Encryptr/issues/156). Haven't tried this myself though.

**Comment by nodiscc** [comment]
awesome-selfhosted should reference the server-side application instead ([Crypton](https://github.com/SpiderOak/crypton)). This doesn't prevent us from linking to the Encryptr client, though I can't find info on where Encryptr stores passwords by default (SpiderOak is mentioned).

**Comment by Kickball** [comment]
I'm read through everything I could find about both Encryptr and Crypton and I'm still not sure if either of them should be on the awesome-selfhosted list.

Unless someone else is able to make sense of these projects it may be best to contact them via te project Github pages.

**Comment by Kickball** [comment]
Closed.

Can be reopened if the project becomes open source.
