### ISSUE TITLE
Disable issues

### ISSUE THREAD

**Issue by jtagcat** [Kickball/awesome-selfhosted#1748]
Make people submit a pull request instead of "I want this to be added".

**Comment by petrk94** [comment]
not a good idea, only because someone has something to add here, it doesnt mean they want to download the repo and make a push etc.
Thats why maintainer exist who take care about this.

**Comment by jtagcat** [comment]
You don't need to download it, you can read 5 sentences for how to contribute, then open the readme.md file and press the edit button, save and create a request. Just follow the green buttons.
If people have anything else to complain, they are very likely to annoy the heck out of other people anyways. ;)

**Comment by nodiscc** [comment]
Issues are used for more than requesting additions.

Even then, having addition requests in the issues tracker doesn't hurt anyone. They will just linger there unless someone takes the time to actually send a patch.

It _does_ take more time to send a proper pull request than to just throw something in issues (I do it also).

If you don't want to see addition requests, you can use [this query](https://github.com/Kickball/awesome-selfhosted/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3Aaddition+).
