### ISSUE TITLE
Gossa doesn't belong in file syncronization.

### ISSUE THREAD

**Issue by jtagcat** [Kickball/awesome-selfhosted#1760]
https://github.com/Kickball/awesome-selfhosted#file-transfersynchronization
found in https://github.com/Kickball/awesome-selfhosted#file-transfersynchronization
rather belongs to https://github.com/Kickball/awesome-selfhosted#web-based-file-managers

**Comment by nodiscc** [comment]
@jtagcat you are right, thanks. Can you fix it?
