### ISSUE TITLE
add a jobs board section?

### ISSUE THREAD

**Issue by chovy** [Kickball/awesome-selfhosted#1772]
I'm interested in self-hosting a job board. Not sure what all there is out there.

**Comment by nodiscc** [comment]
You could ask in one of the communities listed in https://github.com/Kickball/awesome-selfhosted#external-links. I found

 - https://www.jobskee.com/
 - https://github.com/blairanderson/open-source-job-board
 - https://github.com/search?q=job+board

Closing as the chance to get another answer here is slim.
