### ISSUE TITLE
Check Telescope/vulcanjs

### ISSUE THREAD

**Issue by worldworm** [Kickball/awesome-selfhosted#1793]
It looks like the Telescope project moved to vulcanjs.
One would have to take a closer look at both projects to see whether there is a difference here, what changed. Also if vulcanjs should replace Telescope or if it is a seperate entry. Also if vulcanjs is still a selfhosted solution,  currently i think it just looks like a framework..?!

https://github.com/telescopejs/telescope
https://github.com/vulcanjs/vulcan
http://docs.vulcanjs.org/vulcan.html

https://github.com/telescopejs/telescope/issues/10
https://github.com/telescopejs/telescope/issues/16
https://github.com/Kickball/awesome-selfhosted/issues/1767

**Comment by nodiscc** [comment]
http://www.telescopeapp.org/:

> Nova makes building apps easier, but it does require some knowledge of the Node and React ecosystems

Yes it looks like it's only a frameworl/low-level CMS. Let's remove it.
