### ISSUE TITLE
Add Rudder - Rudder is an open-source Segment alternative written in Go, built for the enterprise

### ISSUE THREAD

**Issue by stephane-klein** [Kickball/awesome-selfhosted#1820]
Add [Rudder](https://github.com/rudderlabs/rudder-server) - Rudder is an open-source Segment alternative written in Go, built for the enterprise.

More information : https://news.ycombinator.com/item?id=21081756

**Comment by nodiscc** [comment]
The project is extremely vague about what it does.

> Rudder is an open-source Segment alternative written in Go, built for the enterprise. Rudder is a platform for collecting, storing and routing customer event data to dozens of tools.

If I look up Segment:

>Integrate once. Connect your entire stack.
> Collect, standardize, and activate your customer data in the marketing and analytics tools you need to run your business, all with a single API.

It looks more like a basic building block for custom-built applications. We don't list low-level frameworks and software that don't provide a user-facing service. You may have better luck at https://github.com/n1trux/awesome-sysadmin if you can clearly explain what purpose it serves.

Cheers
