### ISSUE TITLE
add Ajenti to Monitoring and Administration

### ISSUE THREAD

**Issue by liftup** [Kickball/awesome-selfhosted#183]
Ajenti Core
Ajenti Core is a web interface development framework which includes a web server, IoC container, a simplistic web framework and set of core components aiding in client-server communications.

Ajenti Panel

Ajenti Panel consists of plugins developed for the Ajenti Core and a startup script, together providing a server administration panel experience. The Panel’s plugins include: file manager, terminal, notepad, etc.

link http://ajenti.org
Sourcecode https://github.com/Eugeny/ajenti/

**Comment by joubertredrat** [comment]
+1

Ajenti is good solution, I used a lot

**Comment by nodiscc** [comment]
Hi, Ajenti is listed on https://github.com/n1trux/awesome-sysadmin, see #127 #216
