### ISSUE TITLE
Add textbelt for self hosted SMS/text messaging?

### ISSUE THREAD

**Issue by daluu** [Kickball/awesome-selfhosted#192]
See https://github.com/typpo/textbelt

**Comment by nodiscc** [comment]
This _requires_ a third-party service provider (textbelt.com) so I don't think this qualifies as self-hosting.

**Comment by Kickball** [comment]
Closed based on nodiscc comment.

**Comment by daluu** [comment]
That's not true. Recommend a re-open. Did you guys actually read through the readme of the Github project?

The Github project mentions 2 options:

* self host option using the source code on Github, run own instance of the server/API where you route the SMS API requests to email gateways of the telecom carriers. Requires sendmail.
* 3rd party service for those who do not wish to host themselves (textbelt.com API).

The project has a provider list for those who want to do the hacky simplest way by sending their SMS via email directly rather than API of the server, by just using the provided list of email gateways, substituting in the phone # as the email user ID.

https://github.com/typpo/textbelt/blob/master/lib/providers.js

**Comment by david-at** [comment]
I do have to admit this would be a great addition. It takes advantage of the fact that you can email users. Great for monitoring setups!

**Comment by nodiscc** [comment]
@daluu I misread the Github project description and thought it was just a frontend for the service at textbelt.com. The author may want to clarify the description...

> TextBelt (http://textbelt.com) is an outgoing SMS API that uses carrier-specific gateways to deliver your text messages for free, and without ads. The service is fairly reliable and has sent over 100,000 texts.
> Send a text with a simple POST request:
> $ curl -X POST http://textbelt.com/text [...]

A patch to add this application would be accepted (with an ⚠ symbol, as it relies on phone carriers SMS services)

**Comment by nodiscc** [comment]
@david-at @daluu can you submit a pull request to add textbelt?

**Comment by nodiscc** [comment]
Fixed in https://github.com/Kickball/awesome-selfhosted/pull/237
