### ISSUE TITLE
Add Synereo

### ISSUE THREAD

**Issue by pizzamaker** [Kickball/awesome-selfhosted#195]
Under social networks: http://www.synereo.com/  https://github.com/synereo/

**Comment by Kickball** [comment]
I can't seem to find the actual source code in the Github link, so it seems to be closed source.

**Comment by nodiscc** [comment]
Their dockerfiles pull a lot of random git repositories, JARs, etc. and there's no clear build process, so I guess in the current form it can be considered non-Free.

**Comment by Kickball** [comment]
Added in #798.
