### ISSUE TITLE
Add Axis Mundi

### ISSUE THREAD

**Issue by pizzamaker** [Kickball/awesome-selfhosted#196]
A communication platform: https://six-pack.github.io/Axis-Mundi/

**Comment by n8225** [comment]
No license listed in repo or on website.  Opened issue https://github.com/six-pack/Axis-Mundi/issues/27 requesting info.

**Comment by Kickball** [comment]
There have been no commits to the GitHub repo, nor a response to the issue @n8225 opened. Closing for now.
