### ISSUE TITLE
Add Ubuntu One

### ISSUE THREAD

**Issue by pizzamaker** [Kickball/awesome-selfhosted#197]
Canonical recently published the source code for Ubuntu One: https://insights.ubuntu.com/2015/08/10/ubuntu-one-file-syncing-code-open-sourced

**Comment by joubertredrat** [comment]
LOL!
Is serious this? I really liked ubuntu one, now I can to have this server? I will test now

**Comment by Kickball** [comment]
@joubertredrat did you ever get around to testing this?

**Comment by m1guelpf** [comment]
@Kickball Maybe you should close this... #864
