### ISSUE TITLE
Add Cactus Player

### ISSUE THREAD

**Issue by pizzamaker** [Kickball/awesome-selfhosted#211]
http://cactusplayer.com/ Decentralized P2P Music Player

**Comment by nodiscc** [comment]
Ah well. This is a desktop application, so I don't think it can be included. Of course it uses P2P/bittorrent to download songs, but it's still a _client_ application.

@Kickball @pizzamaker please close this issue if you agree.

**Comment by Kickball** [comment]
It does appear to be a client application, the only indication that it is a server application is at the bottom on the page it says:


'This Cactus Player Server Runs: v s0.8.7
This Cactus Player Server is proudly maintained by: Mr.Cactus'

**Comment by MatFluor** [comment]
I downloaded it and saw the following in the welcome "page" of the application:

> ### Host Your Own Server
> 
> Having more Servers greatly increases network stability.
> Therefore, we are looking for people to host their own Cactus Player Server Nodes.
>
> The only thing you need for this is a simple PHP-webhost with a MySQL database. Setting up is very  easy.
> More Information At the [Source repository](https://bitbucket.org/cactusplayer/cactusplayer#markdown-header-how-to-set-up-a-server)

In the bitbucket repo respectively:

> ### How to set up a server
> Setting up a new server is designed to be easy. Requirements:
> A webhost that runs PHP and MySQL.
> Using curl to access remote locations from PHP should be possible.
> ### Setting Up:
> Copy all files from the /server folder to your test server.
> Replace the known_hosts.cphl file with one from your own Client-Side player, which probably  contains more hosts than the included one.
> Edit the settings in config.php so the server can connect to your MySQL database and knows its location on the web.
In PhpMyAdmin, run the included sql/cactus_player_database_structure.sql to set up the database structure. Delete the sql folder afterwards.

So there is an option to host a server **for the network** - but as far as I see, it is _not_ selfhosted (as in _my personal_ cactus server). It would be a cool thing if it had some switches like e.g. on the server "Don't check in to network"or on the client to set "only connect to server X". But the sense of this application is the **distributed** thing. I'm not voting or anything, just some more info for you to decide ;-)

**Comment by Kickball** [comment]
While this is self-hosted it is also distributed, and not for individual use therefore I am closing this issue.
