### ISSUE TITLE
Can I add "Cloud computing"?

### ISSUE THREAD

**Issue by joubertredrat** [Kickball/awesome-selfhosted#214]
Can I add "Cloud computing" topic? I have a lot of options to add in this topic but I need to see If I can create this topic.

**Comment by Kickball** [comment]
Which items on the list do you think would fall under this category?

Can you provide a description of what it will encompass?

**Comment by joubertredrat** [comment]
@Kickball on this category I can add Openstack, Cloudstack, Eucalyptus, Opennebula, oVirt, ContVirt, CC1 and anothers.

**Comment by Kickball** [comment]
Go ahead, just make sure to differentiate it from Groupware and Self-hosting Solutions.

Send the pull request, and if everything meets the formatting guidelines I'll merge it.

**Comment by joubertredrat** [comment]
Okay @Kickball , I will provide this

**Comment by nodiscc** [comment]
Hi everyone

> Openstack, Cloudstack, Eucalyptus, Opennebula, oVirt, ContVirt

https://github.com/n1trux/awesome-sysadmin#cloud-computing already has a cloud computing section and we agreed with @n1trux in https://github.com/Kickball/awesome-selfhosted/issues/127 that we should aim at minimizing overlap between the 2 lists.

What should be done IMHO:

 * @joubertredrat propose your software for inclusion in https://github.com/n1trux/awesome-sysadmin
 * @Kickball let's submit a pull request to move https://github.com/Kickball/awesome-selfhosted/#monitoring-and-administration to awesome-sysadmin.

What do you think? In the long term I'd like system administration software (which "Cloud computing" software really is) to awesome-sysadmin. And only keep server side applications related to other fields in awesome-selfhosted.

We can keep an empty `Monitoring and Administration`, with jut a link _(see https://github.com/n1trux/awesome-sysadmin#monitoring)_ etc.

**Comment by Kickball** [comment]
@nodiscc thanks for catching that. I'd been leaving you to deal with awesome-sysadmin, and I think you've done a good job of it :+1: 

The monitoring and administration section does need to be moved over, however that is a separate issue.

@joubertredrat lets go ahead with what @nodiscc suggested.

**Comment by nodiscc** [comment]
The second part (selfhosted->sysadmin migration) is tracked in #216. @joubertredrat it will also save you time, a lot of software you reference is already in awesome-sysadmin.

Feel free to reopen if needed.
