### ISSUE TITLE
Move Monitoring and Administration to awesome-sysadmin

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#216]
Followup to #214 

> let's submit a pull request to move https://github.com/Kickball/awesome-selfhosted/#monitoring-and-administration to awesome-sysadmin.

**Comment by n1trux** [comment]
I lost track of what we added in awesome-selfhosted and should be deleted from awesome-sysadmin.

If somebody wants to make a PR to replace the "migrated" sections with a link, go on ;)

**Comment by nodiscc** [comment]
@n1trux I am currently comparing the 2 lists, will provide a patch soon (but I need to do some cleanup/section splitting in awesome-selfhosted first)

**Comment by Kickball** [comment]
It looks like this has been completed now (https://github.com/Kickball/awesome-selfhosted/#monitoring), are we good to close this @nodiscc?

**Comment by nodiscc** [comment]
Yes we are :) Remaining work is in https://github.com/Kickball/awesome-selfhosted/issues/127 thanks for the heads up.
