### ISSUE TITLE
Clarification "Private Cloud" vs. "Calendar and address books" vs. "Groupware"

### ISSUE THREAD

**Issue by TwizzyDizzy** [Kickball/awesome-selfhosted#23]
Hi folks,

I do not have a solution yet, but I think there is some overlapping between these three categories.

Any opinions / ideas?

Cheers
Thomas

**Comment by nodiscc** [comment]
Yep owncloud should be moved to "File Synchronization Tools". The seafile entry can be removed (duplicate), and Tine 2.0org can be moved to groupware.

Calendar servers are just well, calendar servers, they have a limited feature set (groupwares also have calendaring features, as well as owncloud). I think they should be kept in a separate section.
