### ISSUE TITLE
add localpaste

### ISSUE THREAD

**Issue by upperhill** [Kickball/awesome-selfhosted#230]
https://github.com/petermaloney/localpaste

a simple python based pastebin you can run locally, with curl for input, just like clbin.com

Supports RAW text by default and binary data such as images(no extensions on returned url).

**Comment by Kickball** [comment]
@AndyR207 @nodiscc @upperhill 
When working to add this to awesome-selfhosted I committed directly to master, please review [the commit](https://github.com/Kickball/awesome-selfhosted/commit/1cd408854d74e9c048ce6a36437175cb04be72f6).

**Comment by nodiscc** [comment]
@Kickball https://github.com/Kickball/awesome-selfhosted/commit/1cd408854d74e9c048ce6a36437175cb04be72f6#diff-04c6e90faac2675aa89e2176d2eec7d8R656

Ideally it should be lowercase.
Missing whitespace at `data such as images(no extensions`
