### ISSUE TITLE
Add Directory Lister

### ISSUE THREAD

**Issue by joubertredrat** [Kickball/awesome-selfhosted#239]
http://www.directorylister.com/

**Comment by joubertredrat** [comment]
I'm looking here, what best topic to input this solution? 
I'd put on awesome sysadmin but I think that repository is "dead".

**Comment by nodiscc** [comment]
The source is at https://github.com/DirectoryLister/DirectoryLister

I think it would fit in [Web based file managers](https://github.com/Kickball/awesome-selfhosted#web-based-file-managers) (it looks similar to Apaxy).

n1trux's [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) is the current active fork; but I think this fits awesome-selfhosted better.
