### ISSUE TITLE
Add Sindex

### ISSUE THREAD

**Issue by joubertredrat** [Kickball/awesome-selfhosted#240]
http://jomppa.net/projects/sindex/

**Comment by joubertredrat** [comment]
https://github.com/Kickball/awesome-selfhosted/issues/239

**Comment by nodiscc** [comment]
Is there an advantage over plain web server directory listings? For example apache's listings have sorting capabiities by default if I remember correctly.

Also no updates since 2010?

**Comment by Kickball** [comment]
This doesn't seem very useful, and doesn't look like it has been updated.
