### ISSUE TITLE
Add a lot of Web Desktop (WebOS)

### ISSUE THREAD

**Issue by joubertredrat** [Kickball/awesome-selfhosted#242]
OneEye (formelly EyeOs) = http://oneye-project.org/
~~Lucid Desktop = http://www.lucid-desktop.org/~~ _https://github.com/lucid/ no updates 2013_
~~CorneliOS = http://www.cornelios.org/~~ _http://www.cornelios.org/web/main/2_downloads/ Please note that the CorneliOS GPL version is no longer being maintained. The last Open Source version is CorneliOS 5.5._
OS.js = http://os.js.org/ _https://github.com/os-js/OS.js maintained BSD Nodejs_
ExtDesk = http://extdesk.net/
Symbiose = http://symbiose.fr.cr/

_Edited 02/18 nodiscc_

**Comment by joubertredrat** [comment]
OneEye = source code only by download
Lucid Desktop = Old project, source code only by download

**Comment by Kickball** [comment]
OneEye and OS.js were added in #826.
