### ISSUE TITLE
Add PHPBack

### ISSUE THREAD

**Issue by joubertredrat** [Kickball/awesome-selfhosted#257]
http://www.phpback.org/
Opensource, PHP
https://github.com/ivandiazwm/phpback/

**Comment by n8225** [comment]
@joubertredrat Why did you close this?

**Comment by joubertredrat** [comment]
This is my issue, why I can't close this?

**Comment by n8225** [comment]
I guess you can, but I'm currently working through adding them.

**Comment by joubertredrat** [comment]
working now after 1 year opened? Isn't necessary, thanks.

**Comment by n8225** [comment]
My apologies, I've only been working on the project a few months.

**Comment by joubertredrat** [comment]
Is not your fall, It is the fault of older maintainers.
