### ISSUE TITLE
Add GitGrep

### ISSUE THREAD

**Issue by joubertredrat** [Kickball/awesome-selfhosted#270]
Opensource code management system for git, similar to Gitlab and Gogs.

http://perlcodesample.sakura.ne.jp/gitprep-site/
https://github.com/yuki-kimoto/gitprep

**Comment by nodiscc** [comment]
@joubertredrat thanks for the many recommendations! Would you like to help adding these entries by sending a pull request? https://github.com/Kickball/awesome-selfhosted/issues/created_by/joubertredrat

**Comment by joubertredrat** [comment]
Hi @nodiscc 
You want one pull request with all mine entries or one by one pull request?

Thanks

**Comment by nodiscc** [comment]
One or multiple pull requests are fine, as long as commit messages mention what's added, and the syntax respects https://github.com/Kickball/awesome-selfhosted/#contributing

**Comment by joubertredrat** [comment]
Hi @nodiscc 
Okay, I will provide this then as one pull request.
Thanks

**Comment by joubertredrat** [comment]
Already on list
