### ISSUE TITLE
Add Mattermost

### ISSUE THREAD

**Issue by joubertredrat** [Kickball/awesome-selfhosted#276]
Opensource chat as alternative to Slack.

http://www.mattermost.org/
https://github.com/mattermost/platform

**Comment by veggiemonk** [comment]
+1

**Comment by nodiscc** [comment]
@veggiemonk can you send a pull request? It would speed things up.

**Comment by veggiemonk** [comment]
Yeah, you're right.... I was just being lazy....  #311

**Comment by Kickball** [comment]
#311 Added this to the repo.
