### ISSUE TITLE
Add Gitea

### ISSUE THREAD

**Issue by joubertredrat** [Kickball/awesome-selfhosted#289]
Opensource code management system for git, forked from Gogs, similar to Gitlab and Gitgub.

Although it be very similar to Gogs, is recent standalone project, with its own features, wiki is an example.

http://gitea.io/
https://github.com/go-gitea/gitea

**Comment by Pe46dro** [comment]
`** THIS PROJECT WILL NOT BE UPDATED, PLEASE VISIT (https://github.com/gogits/gogs) FOR INSTEAD **`

It's discontinued
