### ISSUE TITLE
Add nuages

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#292]
Under _Polls and Events_

https://nuages.domainepublic.net/
http://git.domainepublic.net/?p=nuages.git;a=tree
collaborative meeting poll system, similar to doodle or rdvz. 

python/django
gplv3

**Comment by lcnittl** [comment]
Is it possible that `nuages` is not under active development anymore? The last commit is 4 years old.

Also, the provided link for source does not lead to the project repository (and requires registration).

**Comment by evaryont** [comment]
@lcnittl thanks for the information, but it would be better for you to open a new issue than to bump a long-closed one.
