### ISSUE TITLE
Add BoZoN

### ISSUE THREAD

**Issue by juanito003** [Kickball/awesome-selfhosted#30]
In File Sharing section, you could add BoZoN.
It's like Drop Center/Jirafeau but more recent :
https://github.com/broncowdd/BoZoN/

**Comment by nodiscc** [comment]
@juanito003 can you send a patch? https://help.github.com/articles/editing-files-in-another-user-s-repository/

**Comment by juanito003** [comment]
My patch is here #62

**Comment by nodiscc** [comment]
Moved to https://github.com/Kickball/awesome-selfhosted/pull/62
