### ISSUE TITLE
Add CyTube

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#309]
https://github.com/calzoneman/sync
http://cytu.be/

CyTube is a web application providing media synchronization, chat, and more for an arbitrary number of channels. Support for Synchronized playback from the following sources: `YouTube (individual videos + playlists), Google Docs videos, Vimeo, Dailymotion, Soundcloud, Raw video/audio files, livestream.com, twitch.tv, justin.tv, ustream.tv, RTMP streams, Custom <iframe> and <object> embeds`

**Comment by Kickball** [comment]
Added in #401.
