### ISSUE TITLE
Redmatrix

### ISSUE THREAD

**Issue by juanito003** [Kickball/awesome-selfhosted#31]
You could rename Red -> Redmatrix. The project is currently being rebranded to hubzilla.

**Comment by nodiscc** [comment]
@juanito003 can you send a patch? https://help.github.com/articles/editing-files-in-another-user-s-repository/

**Comment by strugee** [comment]
@nodiscc it's not as simple as editing a file. You need to edit all the translation files, too :/

**Comment by Kickball** [comment]
@strugee assuming @nodiscc is referencing editing the awesome-selfhosted list then there would be no need to edit any translation files.

**Comment by juanito003** [comment]
#61 There is my patch
