### ISSUE TITLE
Add crushpaper

### ISSUE THREAD

**Issue by discipolo** [Kickball/awesome-selfhosted#312]
[crushpaper](https://www.crushpaper.com) - CrushPaper is for students, writers and anyone who writes papers, essays or articles and quotes their sources. ([Demo](https://www.crushpaper.com), [Source code](https://github.com/ZapBlasterson/crushpaper)) `AGPLv3` `Language`

**Comment by nodiscc** [comment]
Waiting for the author to provide some details in https://github.com/ZapBlasterson/crushpaper/issues/2

**Comment by nodiscc** [comment]
> https://github.com/ZapBlasterson/crushpaper/blob/master/doc/Build%2C-Install%2C-Configure-and-Run.md

**Comment by Kickball** [comment]
Added in #827.
