### ISSUE TITLE
Add MailyHerald

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#316]
http://mailyherald.org/
https://github.com/Sology/maily_herald

Ruby/LGPLv3

> helps you send and manage your application mailings. Think of Maily as a self-hosted Mailchimp alternative you can easily integrate into your site. MailyHerald is great both for email marketing and conducting the daily stream of notifications you send to your users.

**Comment by n8225** [comment]
merged with #804
