### ISSUE TITLE
Add OpenSSH/SFTP

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#320]
Under file sharing and synchronization

[OpenSSH](http://www.openssh.com/) provides a secure remote file access protocol called [SFTP](https://wiki.archlinux.org/index.php/SCP_and_SFTP). SFTP shares can be mounted as remote filesystems by many  clients on all platforms.

**Comment by jungle-boogie** [comment]
I wouldn't really think this is a self hosted service as its apart of linux and bsd by default.

**Comment by nodiscc** [comment]
All distributions do not come with openssh-server installed by default. Also SFTP is a very decent and secure file sharing/transfer protocol and should get a mention here. While it _may_ come installed by default, it needs configuration (mainly editing /etc/ssh/sshd_config, authorizing user's SSH keys, and opening firewall ports/forwarding NAT)

**Comment by jungle-boogie** [comment]
Yes, sftp is a great method to share/retrieve data and I'm not meaning to minimize it's use and helpfulness to share data. You should consider adding all OS' to the list and a computer as those too need configuration.

**Comment by nodiscc** [comment]
Many people do not know about SFTP (_how do I setup a file server_ is a recurring question) and for a large majority i would recommend SFTP. The fact that we list web file sharing solutions but not tried-and-true protocols like SFTP/SMB bothers me.

**Comment by jungle-boogie** [comment]
I then recommend a link to Microsoft's openSSH implementation:
https://github.com/PowerShell/Win32-OpenSSH

**Comment by nodiscc** [comment]
You could send a pull request for win32-openssh. It may be preferable to link directly to a page about SFTP (same for linux/bsd openSSH).
