### ISSUE TITLE
Add Samba File Sharing

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#321]
Under file sharing

https://www.samba.org/ -  Samba is the standard Windows interoperability suite of programs for Linux and Unix. It provides secure, stable and fast file and print services for all clients using the SMB/CIFS protocol.

Useful documentation can be found at https://wiki.archlinux.org/index.php/Samba

**Comment by Kickball** [comment]
The Samba [website](https://www.samba.org/) is not linked in the name.

**Comment by nodiscc** [comment]
Fixed in https://github.com/Kickball/awesome-selfhosted/commit/3fe150b25c0d371c22180bb86a4469417ef47aad

**Comment by Kickball** [comment]
Thanks! :smile:
