### ISSUE TITLE
update courier

### ISSUE THREAD

**Issue by lachlan-00** [Kickball/awesome-selfhosted#322]
courier isn't just an imap/pop3 server. It's pretty close to a complete mail server, it even has webmail and can be a relay/proxy for other servers.

http://www.courier-mta.org/#features

Documentation is pretty sparse but i've been running it for a few years for smtp/imap now.

**Comment by nodiscc** [comment]
Thanks for the heads up, I suggest changing the Courier entry as follows:

[Courier MTA](http://www.courier-mta.org/) - Fast, scalable, enterprise mail/groupware server providing ESMTP, IMAP, POP3, webmail, mailing list, basic web-based calendaring and scheduling services. ([Source code](http://www.courier-mta.org/repo.html)) `GPLv3` `C`

@lachlan-00 can you send a pull request?

**Comment by lachlan-00** [comment]
Sure, that's no problem I'll make one tomorrow and add it to the report.

**Comment by lachlan-00** [comment]
https://github.com/Kickball/awesome-selfhosted/pull/325

**Comment by nodiscc** [comment]
Thank you for the patch, closing this now that there's a Pull Request available
