### ISSUE TITLE
Gitter for Self-hosted

### ISSUE THREAD

**Issue by joubertredrat** [Kickball/awesome-selfhosted#329]
Why not? I'm always on Gitter, I can help on channel.

**Comment by nodiscc** [comment]
I think a more decentralized/distributed/standards compliant network (IRC or XMPP) would better suit self hosting communities. Please do some research as I'm sure that such channels/chat rooms already exist.

@Kickball ok to close this?

**Comment by joubertredrat** [comment]
@nodiscc I'm a heavy irc user, we can have channel on freenode and use webclient to connect.

**Comment by nodiscc** [comment]
https://github.com/Kickball/awesome-selfhosted/issues/89
