### ISSUE TITLE
Add Unison

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#347]
https://www.cis.upenn.edu/~bcpierce/unison/

File-synchronization tool over SSH
bi-directional file synchronization/transfer/mirroring with conflicting changes resolution
fast transfers, supports compression, ssh transport, resilient to transfer failures
command line interface + graphical clients, job automation/configuration using profiles

https://help.ubuntu.com/community/Unison
https://wiki.archlinux.org/index.php/Unison
Packaged in most distributions

**Comment by n8225** [comment]
Unison has been added.  Close this issue.
