### ISSUE TITLE
ThinkUp isn't free 

### ISSUE THREAD

**Issue by ToeiRei** [Kickball/awesome-selfhosted#348]
From the FAQ:

>A ThinkUp Membership costs $5 per month and gathers insights from one Twitter account, one >Instagram account and one personal Facebook account. (We don't support Facebook Pages yet.)

+ there is no download. So much about *selfhosted*

**Comment by nodiscc** [comment]
@ToeiRei ThinkUp seem sto be downloadable at https://github.com/ThinkUpLLC/ThinkUp. Installation instructions are at https://www.thinkup.com/docs/. Is there something wrong with this app?

**Comment by ToeiRei** [comment]
In that case the link was misleading as I could not find anything about downloading. All I did see was pricing plans.

**Comment by nodiscc** [comment]
Well, the source code link points to the source.
