### ISSUE TITLE
Ensure all software has a programming language

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#35]
Followup to #14
All new additions should have both license and their main programming language referenced in the list.
Requirement added to CONTRIBUTING section.
Edit: software without license nor language tag can be found with ``egrep -v "\`" README.md``

**Comment by n8225** [comment]
@Kickball @AndyR207 @nodiscc I wasnt paying attention and just merged #741 Could take a look and make sure there aren't any issues.   

Thanks.

**Comment by n8225** [comment]
All entries have languages, closing issue.
