### ISSUE TITLE
Any reasons for not including Textpattern?

### ISSUE THREAD

**Issue by jeanmenezes** [Kickball/awesome-selfhosted#351]
The Textpattern CMS (http://textpattern.com) is a well-established platform powering various websites. I think it would be fair to include it in this list (the most useful and nicely curated I have seen so far).

Cheers!

**Comment by nodiscc** [comment]
@jeanmenezes Thanks, if you can send a patch to add textpattern I'll merge it.

Source code is at https://github.com/textpattern/textpattern
License is GPLv2 http://textpattern.com/license
Language is PHP
Please add it under https://github.com/Kickball/awesome-selfhosted#content-management-systems-cms

https://github.com/Kickball/awesome-selfhosted#contributing

**Comment by nodiscc** [comment]
https://github.com/Kickball/awesome-selfhosted/pull/355

**Comment by Kickball** [comment]
Textpattern CMS was added in #355.
