### ISSUE TITLE
Add NethServer and pfSense

### ISSUE THREAD

**Issue by jadedevin13** [Kickball/awesome-selfhosted#368]
Just try to search for it.

**Comment by nodiscc** [comment]
@jadedevin13 pfSense is already referenced at https://github.com/n1trux/awesome-sysadmin#security. I suggest you file an issue on this repo to get NethServer added (check their [contribution rules](https://github.com/n1trux/awesome-sysadmin/blob/master/CONTRIBUTING.md), basically write about why you want it added)

**Comment by nodiscc** [comment]
NethServer looks interesting but I can't find the source code.

**Comment by e-alfred** [comment]
Well, they have a lot of repositories here:

https://github.com/NethServer

**Comment by evaryont** [comment]
NethServer seems to be more of a Linux distribution rather than an individual piece of software. We don't list every Debian derivative, nor every RedHat one. I don't think we should start doing so now.

**Comment by e-alfred** [comment]
@evaryont Well, it allows people to selfhost a lot of software ranging from Active Directory to Nextcloud and much more. In that regard it is similar to DietPI and Yunohost which also attempt to make selfhosting easier in an awesome way (which is the reason for this list anyway).

**Comment by evaryont** [comment]
I do appreciate that, and perhaps it's focus on making self-hosting easier does warrant further consideration for inclusion in this list, but I'm not the one who makes that decision. I'll leave it up to @Kickball and @nodiscc
