### ISSUE TITLE
Add NgRok

### ISSUE THREAD

**Issue by jadedevin13** [Kickball/awesome-selfhosted#375]
Basically it's like pagekite.

https://ngrok.com/

**Comment by nodiscc** [comment]
ngrok tunnels connections to your personal server through their own infrastructure (actual transmitted data)

> ngrok.com does log some information about the connections which are used for debugging purposes and metrics like the name of the tunnel and the duration of connections

So this is not something I would recommend for awesome-selfhosted (putting a third-party in a position to sniff all your traffic). However both the client and server seem to be Free Software (https://packages.debian.org/search?keywords=ngrok). @jadedevin13 I suggest you send this request to https://github.com/n1trux/awesome-sysadmin instead.

@Kickball ok to close this?

**Comment by Kickball** [comment]
Yeah, we're alright to close this, it is better suited for awesome-sysadmin.
