### ISSUE TITLE
Look into teknik.io services and software

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#376]
More self-hostable software can be found at http://git.teknik.io/org/Teknikode (https://www.teknik.io)

**Comment by Kickball** [comment]
The git link is now a 404, and the teknik website link has contains a lot of content.

Could you provide a direct to the self hosted found there?

**Comment by nodiscc** [comment]
I can't find it anymore. I also recall it required an ASP.net/Microsoft server stack. Closing.
