### ISSUE TITLE
Add Screaming Liquid Tiger

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#404]
https://github.com/herrbischoff/screaming-liquid-tiger - Simple script to automatically generate valid RSS and Atom feeds from a list of media files in the same folder `MIT` `PHP`

**Comment by Kickball** [comment]
a4b3efd of #408 adds Screaming Liquid Tiger.

**Comment by Kickball** [comment]
#408 has been merged, and added this.
