### ISSUE TITLE
Add eZ Server Monitor

### ISSUE THREAD

**Issue by shevabam** [Kickball/awesome-selfhosted#413]
[eZ Server Monitor](http://www.ezservermonitor.com) - A lightweight and simple dashboard monitor for Linux, available in Web and Bash application. ([Source code](https://github.com/shevabam/ezservermonitor-web)) `GPL` `BashScript/PHP`

Under *Monitoring and Administration* category.

**Comment by Kickball** [comment]
@nodiscc are we moving all of the Monitoring and Administration category to Awesome-Sysadmin?

**Comment by nodiscc** [comment]
I think we are. @shevabam  as a part of [this work](https://github.com/Kickball/awesome-selfhosted/search?utf8=%E2%9C%93&q=awesome-sysadmin&type=Issues) we are moving all system administration-related software to https://github.com/n1trux/awesome-sysadmin. Can you submit your patch there (check if eZ Server Monitor is already included beforehand)?

**Comment by shevabam** [comment]
Ok, no problem ;)
Thanks !
