### ISSUE TITLE
Add HRM systems

### ISSUE THREAD

**Issue by GuzziGuy** [Kickball/awesome-selfhosted#427]
Fab list - hugely useful! Am looking to install a HR/personnel system - it would be useful to have a section on here for them. OrangeHRM seems the notable one - but I think there are at least a couple of others around; IceHRM, Sentrifugo.

**Comment by AndyR207** [comment]
If you have a couple of systems in mind and want to add them to the list, feel free to create a PR. Make sure that the section you add is in alphabetical order etc... in accordance with our [contributing guidance](https://github.com/Kickball/awesome-selfhosted#contributing).

**Comment by n8225** [comment]
Merged in #883

**Comment by greggluhring** [comment]
Remove me


On December 16, 2016 6:01:20 PM n8225 <notifications@github.com> wrote:

Closed #427.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Kickball/awesome-selfhosted/issues/427#event-897405798

**Comment by greggluhring** [comment]
I told you I would do this months ago you didn't believe me just take me 
this freaking list.


On December 16, 2016 6:01:20 PM n8225 <notifications@github.com> wrote:

Merged in #883

**Comment by greggluhring** [comment]
Please remove me it cannot be that hard it's really easy though ignore a 
noob I know


On December 16, 2016 6:01:20 PM n8225 <notifications@github.com> wrote:

Merged in #883

**Comment by nodiscc** [comment]
> Please remove me it cannot be that hard it's really easy though ignore a noob I know

@greggluhring If you're talking about unsubscribing you from notifications on this repo/your issues, we can't do it for you, Github provides us no way of doing that. Only _you_ can unsubscribe (manually) from each issue you've created/subscribed to (button on the right-hand side).
