### ISSUE TITLE
Add awesome-bigdata to External Links Section

### ISSUE THREAD

**Issue by Kickball** [Kickball/awesome-selfhosted#430]
As per [this](https://www.reddit.com/r/selfhosted/comments/43yrib/looking_for_a_self_hosted_asset_management_system/czn0d28) reddit comment we could consider adding [awesome-bigdata](https://github.com/onurakpolat/awesome-bigdata) as one of the external links.

**Comment by nodiscc** [comment]
:+1:

**Comment by Kickball** [comment]
Pull request #432 has been merged and added this license.
