### ISSUE TITLE
add hydrus network

### ISSUE THREAD

**Issue by pokeball99** [Kickball/awesome-selfhosted#433]
github.com/hydrusnetwork/hydrus
not sure exactly what category it would go in

**Comment by nodiscc** [comment]
https://hydrusnetwork.github.io/hydrus/:

> The hydrus network client is a desktop application

Therefore I don't think it is a good fit for this list (which focuses on network services)

**Comment by pokeball99** [comment]
@nodiscc this is basicly an self hosted version of booru type imageboards, with a client/server setup if one wanted to collaborate/sync on tagging files, plus the fact of the upcoming feature of ipfs support.

**Comment by nodiscc** [comment]
@pokeball99 If you can point us at the server-side software that would be nice.

**Comment by pokeball99** [comment]
@nodiscc https://github.com/hydrusnetwork/hydrus/blob/master/server.py

**Comment by Kickball** [comment]
While the server information has been provided by @pokeball99, the quality of the code and documentation is low enough to warrant rejecting this project.

We can reopen this once the quality of the project overall has improved.
