### ISSUE TITLE
IRCanywhere not maintained anymore?

### ISSUE THREAD

**Issue by ToeiRei** [Kickball/awesome-selfhosted#436]
I was trying to find help at the support channel for IRCanywhere. Interesting find was the topic of the channel:

> - Now talking on #ircanywhere
> - Topic for #ircanywhere is: Project is no longer being actively maintained. For hilarity, see: ##topkek, for IRC Clients, see: The Googlez
> - Topic for #ircanywhere set by Gnasher!~Gnasher@apollo.flvrs.com (Wed Sep 23 16:27:10 2015)
 > -ChanServ-	[#ircanywhere] Be patient asking for help, we're not around 24/7. If nobody is answering please report your issue on the bug tracker at https://github.com/ircanywhere/ircanywhere/issues

**Comment by nodiscc** [comment]
Hi, there still is some activity at https://github.com/ircanywhere/ircanywhere/commits/development (last commits in Nov 2015 with at least 1 active maintainer, and patches from other users/devs). The application seems to be working, and has an active user community. The IRC channel topic indeed contradicts this; you may want to ask @rickihastings about the state of the project (as the channel topic implies, on https://github.com/ircanywhere/ircanywhere/issues)

**Comment by AndyR207** [comment]
If it still works properly, I don't see any reason to remove it from the list.

**Comment by nodiscc** [comment]
Please reopen if needed.
