### ISSUE TITLE
Tools: automatic sorting of entries/sections

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#460]
A script/Makefile that would take care of reordering sections, and entries inside them would be welcome. Alternatively it could just just emit a warning when things are not properly sorted.

**Comment by cpdevelops** [comment]
I think that this would be a great idea but I think that something that would be interesting is the automatic addition of more programs using a script.

**Comment by nodiscc** [comment]
This is already _partially_ possible: run [`make add`](https://github.com/Kickball/awesome-selfhosted/blob/master/Makefile#L35). This only generates an entry with the correct syntax. You need to copy-paste it to README.md.
