### ISSUE TITLE
Domain for Awesome-Selfhosted related sites

### ISSUE THREAD

**Issue by Kickball** [Kickball/awesome-selfhosted#465]
@AndyR207 @nodiscc I'm looking to rent a new domain for this repo, it will allow us to host the site Andy is working on in the awesome-selfhosted-scanner repo. We can also use this domain to host the list once it is converted into a taggable format.

My current considerations for names are:
* selfhosted.systems
* selfhosted.solutions
* awesome-selfhosted.com
* selfhosted-aweso.me

Please feel free to edit this issue and add in more considerations, once we have gathered potential domains I'll arrange a vote.

**Comment by AndyR207** [comment]
I don't mind, any work for me.

**Comment by nodiscc** [comment]
My votes in order:

1. selfhosted-aweso.me
2. selfhosted.systems
3. selfhosted.solutions
4. awesome-selfhosted.com

**Comment by nodiscc** [comment]
Is it doable to host a Gitlab or Gogs instance on this domain? We could setup a mirror of https://github.com/Kickball/awesome-selfhosted

**Comment by AndyR207** [comment]
@nodiscc I might be able to spare some server resources for it.

**Comment by pengc99** [comment]
I have tons of datacenter server resources available!

**Comment by cleverdevil** [comment]
DreamHost is definitely interested in contributing! I'm sending my Community guy over here right now :)

**Comment by AndyR207** [comment]
@nodiscc -- @Kickball and I have been discussing this and have a few concerns with it. Primarily the fact that it only links back to this repo are on the contribute page, most of the other content suggests that it's curated/owned by LibHunt (which while their UI might be, the list is not).

Additionally, their contribute page does not have fields for all the different items we actually request (missing demo and license, for example).

**Comment by nodiscc** [comment]
The About page mentions that this repository is the source for their data, however is also believe this kind of attribution is insufficient - the about page should contain a copy of the [License section](https://github.com/Kickball/awesome-selfhosted#license).

ping @libhunt

**Comment by StanBright** [comment]
Hello everyone,

@nodiscc, first, thanks for suggesting selfhosted.libhunt.com! Second, you are right, I will have to state somewhere that the data is CC-BY-SA. I've added that to my todo, and I hope that will be online soon. 

@nodiscc, @Kickball, I'm currently working on the functionality to extract licenses from different libs automatically. Once that is ready there will be licenses listed alongside every entry.

If you are not going use [selfhosted.libhunt.com](https://selfhosted.libhunt.com) for the domain of this repo, I would vote, if I may, for awesome-selfhosted.com. Also, based on my experience, I think that the hack-ish "selfhosted-aweso.me" isn't a top choice.

**Comment by nodiscc** [comment]
@StanBright thanks for taking the time to reply; any updates? You are welcome to use the list for your site, but you must comply to the following license terms:

https://creativecommons.org/licenses/by-sa/3.0/deed.en

In particular

>you must provide the name of the creator and attribution parties, a copyright notice, a license notice, a disclaimer notice, and a link to the material.

It simply requires copying our license section (with full contributors list) to your About page, and mention in the footer (on pages where the data is displayed) that the list is under CC-BY-SA 3.0 (linking to https://creativecommons.org/licenses/by-sa/3.0/deed.en).

Please let us know if you have questions.

**Comment by Kickball** [comment]
@nodiscc thank you for clarifying the license situation.

An email has been sent to the email found on your Github profile as we have been trying to get in touch with you regarding the future plans for this project. If you have not received anything please send me an email to the one found on my Github profile.

**Comment by nodiscc** [comment]
@StanBright :+1: thanks for placing a CC-BY-SA logo/link on your site, and for updating https://selfhosted.libhunt.com/terms. You're welcome to forward us future contributions made by users of your site.

**Comment by Kickball** [comment]
Going to close this as we have bought the domains:

* https://awesome-selfhosted.com (primary)
* https://awesomeselfhosted.com
