### ISSUE TITLE
Missing Licenses

### ISSUE THREAD

**Issue by Kickball** [Kickball/awesome-selfhosted#471]
The following issues where identified in awesome-selfhosted by @AndyR207:

    [Countly](https://count.ly) - Real time mobile & web analytics, crash reporting and push notifications platform ([Source Code](https://github.com/countly)) `AGPL` `Javascript`
- [x]  Demo needs to come Before Source Code

    [Bookie](https://github.com/bookieio/Bookie) - Python based delicious.com replacement. ([Firefox addon](https://github.com/bookieio/bookie-firefox), [Demo](http://bmark.us/), [Documentation](http://docs.bmark.us/) `unlicensed` `Python`
Firefox Addon and Documentation are not valid. Please remove them. Please capitalize "Unlicensed" although I feel like this entire entry should be removed because I don't think we're accepting "Unlicensed" as a valid thing?? @Kickball @nodiscc AGPLv3, fixed -- nodiscc

    [Firefox Sync Server](https://docs.services.mozilla.com/howtos/run-sync-1.5.html) - Sync Firefox bookmarks, passwords, history, tabs, preferences. ([Source Code](https://github.com/mozilla-services/syncserver)) `unlicensed` `Python`
See above comment about licensing. -- MPLv2, fixed -- nodiscc

    [Lobsters](https://lobste.rs) - Run your own link aggregation site. ([Source Code](https://github.com/jcs/lobsters))
- [x] No license 
- [x] No language

    [Shaarli](https://github.com/shaarli/Shaarli) - Personal, minimalist, super-fast, no-database bookmarking and link sharing plaform. ([Demo](http://shaarlidemo.tuxfamily.org/Shaarli/) `demo/demo`) `Zlib` `PHP`
- [x] Remove the demo/demo part -- these are the demo credentials and they should be kept -- _nodiscc 2016-02-27_

    [calypso](http://keithp.com/calypso/) - A python-based CalDAV/CardDAV server. ([Source Code](http://keithp.com/cgi-bin/gitweb.cgi?p=calypso.git;a=tree)) `GPLv3`
- [x] Missing language

    [DAViCal](http://www.davical.org/) - A server for calendar sharing (CalDAV). ([Source Code](https://gitlab.com/davical-project/davical)) `MIT`
- [x] Missing language

    [ownCloud calendar](https://doc.owncloud.org/server/7.0/user_manual/pim/calendar.html) - The ownCloud Calendar app enables you to create and edit events, synchronize to other calendars you might use, and create new, personalized calendars. ([Source Code ownCloud < 9](https://github.com/owncloud/calendar), [Source Code ownCloud 9+](https://github.com/owncloud/calendar-rework)) `AGPLv3` `PHP`
- [x] remove one source code links
- [x] change the label to just "Source Code"

    [Kandan](http://getkandan.com/) – Kandan is an Open Source Alternative to HipChat. ([Source Code](https://github.com/kandanapp/kandan)) `AGPLv3` `Ruby`
- [x] hypen needs to be a short hyphen as opposed to a long one

    [Lets-Chat](http://sdelements.github.io/lets-chat/) - A self hosted chat suite written in Node. ([Source](https://github.com/sdelements/lets-chat)) `MIT` `JavaScript, NodeJS`
- [x] Source -> Source Code

    [Rocket.Chat](https://rocket.chat/) – Teamchat solution similar to Gitter.im or Slack. ([Source Code](https://github.com/RocketChat/Rocket.Chat)) `MIT`
- [x] Missing language

    [hMailServer](https://www.hmailserver.com) - Open source e-mail server for Microsoft Windows. ([Source Code](https://github.com/hmailserver/hmailserver)) `C++`  
- [x] Missing License

     [iRedMail](http://www.iredmail.org/) - Full-featured mail server solution based on Postfix and Dovecot.
- [x] Missing license
- [x] Missing language

    [Citadel](http://www.citadel.org/) - Feature packed, easy, versatile, and powerful mail server, thanks to exclusive "rooms" based architecture. ([Source Code](http://code.citadel.org/?p=citadel.git;a=summary))
- [x] Missing license  (#590)
- [x] Missing language (#590)

    [Exim](http://www.exim.org/) - Message transfer agent (MTA) developed at the University of Cambridge. `GPL`
- [x] Missing language (#591)

    [OpenSMTPD](https://opensmtpd.org/) - Secure SMTP server implementation from the OpenBSD project. `ISC`
- [x] Missing language (#592)

    [Qmail](http://www.qmail.org/top.html) - Secure Sendmail replacement. `CC0`
- [x] Missing language (#593)

    [Sendmail](http://www.sendmail.com/sm/open_source/) - Message transfer agent (MTA).
- [x] Missing license 
- [x] Missing language

    [Cyrus IMAP/POP3](http://cyrusimap.org/) - Intended to be run on sealed servers, where normal users are not permitted to log in.
- [x] Missing license
- [x] Missing language

    [Roundcube](https://roundcube.net) - Browser-based IMAP client with an application-like user interface. ([Screenshots](https://roundcube.net/screens/)) ([Source Code](https://github.com/roundcube/roundcubemail/)) `GPLv3` `PHP`
- [x] Remove Screenshots

    [Asterisk](http://www.asterisk.org/) - An easy to use but advanced IP PXB system, VoIP gateway and conference server `GPLv2` `C`
- [x]  full stop needed after the description

    [FreeSWITCH](https://freeswitch.org/) - Scalable open source cross-platform telephony platform ([Source Code](https://freeswitch.org/stash/projects/FS/repos/freeswitch/browse)) `MPLv2` `C`
- [x]  full stop needed after the description

    [Kamailio](http://www.kamailio.org/w/) - Modular SIP server (registrar/proxy/router/etc) ([Source Code](https://github.com/kamailio/kamailio)) `GPLv2` `C`
- [x]  full stop needed after the description

    [Ostel](https://dev.guardianproject.info/projects/ostel/wiki/Server_Documentation) - Secure SIP telephony setup with ZRTP encryption `GPLv3` `Ruby`
- [x]  full stop needed after the description

    [Friendica](http://friendica.com/) - Social Communication Server. ([Source Code](https://github.com/friendica/friendica)) `AGPLv3`
- [x] Missing language

    [Jappix](https://jappix.com/) - Jappix is an open social platform, that let's you easily get or keep in touch with everyone. ([Source Code](https://github.com/jappix/jappix)) `AGPLv3`
- [x] Missing language

    [Loomio](https://www.loomio.org/) - Loomio is a collaborative decision-making tool that makes it easy for anyone to participate in decisions which affect them.  ([Source Code](https://github.com/loomio/loomio)) `AGPLv3` `Ruby`
- [x] Remove double space after description

    [Oxwall](http://www.oxwall.org/) Oxwall is used for a wide range of projects starting from family sites and custom social networks to collaboration tools and enterprise community solutions. ([Source Code](https://bitbucket.org/oxwall/public) `CPALv1` `PHP`
- [x] Missing hyphen between URL and description
- [x] Missing closing bracket after Source Code

    [PPnet](https://github.com/pixelpark/ppnet) Create and host your own social network. `MIT` `JavaScript`
- [x] Missing hyphen between URL and description

    [Reddit](https://www.reddit.com/) - Social networking and news website where registered community members can submit content. ([Demo](https://www.reddit.com/) [Source Code](https://github.com/reddit/reddit)) `CPALv1` `Python`
- [x] Missing full stop

    [htmly](https://www.htmly.com/) - Databaseless Blogging Platform (Flat-File Blog). ([Source Code]((https://github.com/danpros/htmly)), [Demo](https://www.htmly.com/demo/)) `GPLv2` `PHP`
- [x] Missing comma after demo link

    [ejabberd](https://www.ejabberd.im/) - XMPP instant messaging server. ([Source](https://github.com/processone/ejabberd)) `GPL` `Erlang`
- [x] Source -> Source Code

    [Metronome IM](https://lightwitch.org/metronome) - Fork of Prosody IM. ([Source](http://code.lightwitch.org/)) `MIT` `Lua`
- [x] Source -> Source Code

    [MongooseIM](https://www.erlang-solutions.com/products/mongooseim.html) - Fork of ejabberd. ([Source](https://github.com/esl/MongooseIM)) `MIT` `Erlang`
- [x] Source -> Source Code

    [Openfire](http://www.igniterealtime.org/projects/openfire/) - Real time collaboration (RTC) server. ([Source](https://github.com/igniterealtime/Openfire)) `Apache` `Java`
- [x] Source -> Source Code

    [Prosody IM](http://prosody.im/) - Feature-rich and easy to configure XMPP server. ([Source](http://hg.prosody.im/)) `MIT` `Lua`
- [x] Source -> Source Code

    [Tigase](http://www.tigase.net/content/tigase-xmpp-server) - XMPP server implementation in Java. `Java`
- [x] Missing license

    [Candy](http://candy-chat.github.io/candy/) - Multi user XMPP client written in Javascript. ([Source](https://github.com/candy-chat/candy)) `MIT` `JavaScript`
- [x] Source -> Source Code

    [Converse.js](https://conversejs.org/) - A free and open-source XMPP chat client in your browser ([Source](https://github.com/jcbrand/converse.js)) `MPLv2` `Javascript`
- [x] Full stop after description
- [x] Source -> Source Code

    [Kontalk](http://kontalk.org/) – Kontalk is an Open Source Messenger, similiar to WhatsApp (app for android only currently), including end-to-end encryption, server is based on Tigase XMPP Server - ([Source Code](https://github.com/kontalk)) `GPLv3`
- [x] Hyphen needs replacing with short hypen
- [x]  Bad brackets
- [x] needs full stop after the description not a hyphen
- [x] missing language

    [Libervia](http://wiki.goffi.org/wiki/Libervia/en) - Web frontend from Salut à Toi ([Source Code](http://repos.goffi.org/libervia)) `AGPLv3` `Python`
- [x] Missing full stop after description

    [99ko CMS](http://www.99ko.org/) - 99ko allows you to create a website in minutes without knowledge of Web development. It does not use a database server but relies on simple text files (JSON format) to store your data. ([Source Code](https://github.com/99ko-project/99ko-cms))
- [x] Missing license 
- [x] Missing language

    [GetSimple CMS](http://get-simple.info/) - The Simplest Content Management System. Ever. `GPLv3`
- [x] Missing language

    [ImpressPages CMS](https://www.impresspages.org/) - Easy code meets easy admin. ([Demo](https://www.impresspages.org/demo), [Source Code](https://github.com/impresspages/ImpressPages)) `GPLv3`/`MIT`  `PHP`
- [x] Dual language needs to removed or condensed -- _dual license, not language -- nodiscc_
- [x] Remove double space between license and language

    [daloRADIUS](http://www.daloradius.com) - Open-source web management platform for FreeRADIUS-based deployments. ([Source Code](https://github.com/lirantal/daloradius)) `GPLv2`
- [x] Missing language

    [OpenCA OCSPD](https://pki.openca.org/projects/ocspd/) - An [OCSP](https://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol) Responder.
- [x] Missing license
- [x] Missing language

    [OpenID/OpenID Connect](http://openid.net/developers/libraries/) - A Simple Identity layer on top of OAuth 2.0
- [x] Missing full stop after description
- [x] Missing license 
- [x] Missing language

**Comment by Kickball** [comment]
68cd806 fixes a few of the issues listed above. I clicked the enter key accidentally, and it pushed directly to master with an incomplete commit message. @nodiscc @n8225 @AndyR207 please give it a look over to make sure all of the changes were good.

**Comment by n8225** [comment]
I'm not seeing any issues in the commit.

**Comment by Kickball** [comment]
@nodiscc @n8225 @AndyR207 We've tackled most items in this list (but it looks like our scanners have found more for us to fix), but OpenID/OpenID Connect is still missing language and license.

I've given the site a look over and can't seem to find a license or the programming language. Can anyone give finding them a shot?

**Comment by nodiscc** [comment]
@Kickball there are libraries/modules/... in every language and with many licenses to implement OpenID in your own services ([this page](https://openid.net/developers/libraries/) lists them. Some are meant to be integrated into applications to make them work with an external OpenID Identity Provider, some are Identity providers by themselves, some are webserver modules...

In fact I'd rather remove this entry from the list completely. From [Wikipeda](https://en.wikipedia.org/wiki/OpenID):

> OpenID is an open standard and decentralized authentication protocol.

We don't list standards, protocols, or libraries, so I'd rather remove OpenID from the list and someone can submit a patch later for the OpenID "server" software of their choice. As far as I remember this entry was added early, when the guidelines were not very clear.

**Comment by Kickball** [comment]
@nodiscc I was feeling the same way. It doesn't fit with our guidelines or the other entries in the list. I'm happy to remove and will submit a PR for it soon. (ping @n8225 @AndyR207 to make sure you're both in the loop)

**Comment by n8225** [comment]
Openid was removed with #729

**Comment by Kickball** [comment]
As OpenID has been dealt with as @n8225 said we have completed all items on this list. I'm closing the issue.
