### ISSUE TITLE
Add MistServer

### ISSUE THREAD

**Issue by R0GGER** [Kickball/awesome-selfhosted#482]
**Description:** 
MistServer is a streaming media server that works well in any streaming environment even a Raspberry Pi! It bridges the gap between dedicated media servers and web servers, performing the best of both worlds when it comes to media streaming delivery.

**Comment:**
Very easy to configure, low resources, works well with OBS (hls) and in Docker! Great software!

**Links:**
Website: http://mistserver.org
Github: https://github.com/DDVTECH/mistserver
Docker: https://hub.docker.com/r/ddvtech/mistserver/

**Cat:** 
Video Streaming

**Comment by n8225** [comment]
Added with #792
