### ISSUE TITLE
Add Open Food Network

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#486]
https://openfoodnetwork.org/
https://github.com/openfoodfoundation/openfoodnetwork
AGPL, Ruby

The Open Food Network is an online marketplace for local food. It enables a network of independent online food stores that connect farmers and food hubs (including coops, online farmers' markets, independent food businesses etc); with individuals and local businesses. It gives farmers and food hubs an easier and fairer way to distribute their food.

**Comment by n8225** [comment]
Added with #792
