### ISSUE TITLE
Remove remaining static site generators

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#506]
As discussed in https://github.com/Kickball/awesome-selfhosted/pull/501, we should remove entries that are present both in our list and on https://staticsitegenerators.net/ or https://www.staticgen.com/.

Grav is subject to removal, there may be others.

**Comment by Kickball** [comment]
Both of those lists are too long to check manually, to properly check these lists entirely we will most likely have to write a script to scrape all of the names on both lists and search awesome-selfhosted for those project names.

**Comment by nodiscc** [comment]
It might be worth checking only our CMS and Wikis sections against those lists (a static site generator is less likely to appear in another category)

 - [ ] remove ikiwiki

**Comment by Kickball** [comment]
I have just checked through every entry in our CMS, Wiki and Blog sections, I updated @nodiscc's above comment with the duplicates found. #721 is a PR to remove the identified duplicates.
