### ISSUE TITLE
Add Bitstorm bittorrent tracker

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#517]
A simple bittorrent tracker contained in a single PHP file

Original page is at https://stormhub.org/tracker/ui.php, source at https://stormhub.org/tracker/ui.php

Date of last update is unknown, but it could be considered simple enough to not require significant maintenance. It might be worth looking for current forks (eg. https://github.com/search?q=bitstorm&s=stars&type=Repositories) before including it.

**Comment by Kickball** [comment]
The site has gone down and there seem to be no updated forks. Should we close this?

**Comment by nodiscc** [comment]
Indeed.
