### ISSUE TITLE
Add Dot Ledger (Accounting)

### ISSUE THREAD

**Issue by Kickball** [Kickball/awesome-selfhosted#518]
Dot Ledger is accounting software, however I am having trouble identifying if it is server software or just client software (making it invalid for this list).

* [Dot Ledger](https://www.dotledger.com/#home) - Dot Ledger is a web-based personal finance management tool, with features such as: transaction categories, sorting rules and planned payments. ([Source Code](https://github.com/dotledger/dotledger), [Demo](https://demo.dotledger.com/)) `Apache 2.0` `Ruby`

**Comment by Chouchen** [comment]
Leger or Ledger ?

**Comment by Kickball** [comment]
I have corrected Leger to Ledger, thanks for the comment.

**Comment by nodiscc** [comment]
@Kickball it can be accessed through a web browser (https://demo.dotledger.com/) remotely so this fits the web application criteria.

**Comment by n8225** [comment]
Added with #792
