### ISSUE TITLE
Find some SEO analytics/tracking tools

### ISSUE THREAD

**Issue by HammyHavoc** [Kickball/awesome-selfhosted#541]
Most of these seem to only be available as SaaS, would love to find some new stuff to self-host.

**Comment by nodiscc** [comment]
Any example? We have several analytics projects in https://github.com/Kickball/awesome-selfhosted#analytics. Feel free to ask at https://reddit.com/r/selfhosted

**Comment by HammyHavoc** [comment]
Stuff like AWR (Advanced Web Rankings), SERP Lab, SERP Fox, that kind of thing. It's a real gap from what I've experienced with self-hosting, things like a Raspberry Pi are perfect for this kind of monitoring if there's any available scripts.
