### ISSUE TITLE
Add a dummy DNS servers section

### ISSUE THREAD

**Issue by AminaG** [Kickball/awesome-selfhosted#548]
Any one know about Awesome DNS Server?

**Comment by vrutkovs** [comment]
https://www.unbound.net/ is good

**Comment by samgaw** [comment]
NTP Pool's Geo DNS server - https://github.com/abh/geodns (ASLv2)
PowerDNS - https://github.com/PowerDNS/pdns (GPLv2)

**Comment by Kickball** [comment]
A DNS server would not fall under awesome-selfhosted, instead under awesome-sysadmin.

[Here](https://github.com/n1trux/awesome-sysadmin#dns) are there DNS servers.

**Comment by nodiscc** [comment]
https://github.com/n1trux/awesome-sysadmin#dns

@Kickball should we add a section like https://github.com/Kickball/awesome-selfhosted#web-servers for DNS?

**Comment by AndyR207** [comment]
@nodiscc sure, seems like a good idea.

**Comment by AminaG** [comment]
I recommend [bind](https://www.isc.org/downloads/bind/)
