### ISSUE TITLE
Add GNUnet

### ISSUE THREAD

**Issue by pizzamaker** [Kickball/awesome-selfhosted#55]
GNUnet, under Communication Systems

https://en.wikipedia.org/wiki/GNUnet

**Comment by nodiscc** [comment]
> a free software framework for decentralized, peer-to-peer networking 

you mean under communication systems

**Comment by pizzamaker** [comment]
correct!

**Comment by nodiscc** [comment]
@pizzamaker can you send a patch? https://help.github.com/articles/editing-files-in-another-user-s-repository/
