### ISSUE TITLE
Text-based RPG or relative?

### ISSUE THREAD

**Issue by gravcat** [Kickball/awesome-selfhosted#558]
Checking in the games section, it is somewhat lacking. Is anyone aware of or has personal experience with self-hosting a text-based game, such as nethack-type stuff? I'd love to see input that would be able to make it in as a contribution, but I am not sure of the options.

**Comment by Kickball** [comment]
Some games were added in #558. Discussions will be moved to [chat](https://chat.awesome-selfhosted.com/).
