### ISSUE TITLE
Subsonic is no longer open source

### ISSUE THREAD

**Issue by ola-** [Kickball/awesome-selfhosted#559]
[according to the author](http://forum.subsonic.org/forum/viewtopic.php?f=4&t=16604#p71128).

Replace listing with [libresonic](https://github.com/Libresonic/libresonic)?

**Comment by alexfornuto** [comment]
https://github.com/Kickball/awesome-selfhosted/pull/550

**Comment by Kickball** [comment]
Closed as duplicate of #550.
