### ISSUE TITLE
add COPS - a nice calibre server replacement

### ISSUE THREAD

**Issue by rbrok** [Kickball/awesome-selfhosted#566]
Calibre OPDS (and HTML) PHP Server : web-based light alternative to Calibre content server / Calibre2OPDS to serve ebooks (epub, mobi, pdf, ...) http://blog.slucas.fr/en/oss/calibre-opds-php-server

Demo: http://cops-demo.slucas.fr/index.php

**Comment by Kickball** [comment]
Added in #827.
