### ISSUE TITLE
add Duet - Self-Hosted Project Management System

### ISSUE THREAD

**Issue by Edreih** [Kickball/awesome-selfhosted#572]
https://duetapp.com/ (paid one-time fee)

Related:
http://www.getsoloapp.com/ (free version of Duet)
http://theanchorapp.com/ (free Invoice and Payments management self hosted app)

I've used these and they work pretty great.

**Comment by Edreih** [comment]
Update: Created pull requests with these.

**Comment by Kickball** [comment]
These were added in #574 and #588.
