### ISSUE TITLE
Kolab entry is missing information

### ISSUE THREAD

**Issue by aveeshkumar** [Kickball/awesome-selfhosted#578]
Hi,

I could be wrong but Kolab (groupware) now is only pay as a service with no self hosted / community editions that I could find

**Comment by nodiscc** [comment]
Hi, the sources seem to be available [here](https://git.kolab.org/diffusion/).  
Install instructions are [here](https://docs.kolab.org/installation-guide/index.html)  
Most of their code [seems to be under the GPLv2](https://git.kolab.org/diffusion/LK/browse/master/COPYING), though [Wikipedia](https://en.wikipedia.org/wiki/Kolab) states that it uses multiple Free Software licenses.

@aveeshkumar If you want to edit the Kolab entry which is currently incomplete (misses source code link, license and languages - C++/Python/PHP), a Pull Request would be welcome.

**Comment by aveeshkumar** [comment]
Sorry - newbie anxiety!




Aveesh
--------------------------------------------------
Verified Virus Free by Gmail
