### ISSUE TITLE
Concerns over Tine20 as FLOSS

### ISSUE THREAD

**Issue by Kickball** [Kickball/awesome-selfhosted#595]
@AndyR207 @nodiscc 

Tine 2.0 (found in the [groupware section](https://github.com/Kickball/awesome-selfhosted#groupware)) is current on our normal FLOSS list. Tine's [website](http://www.tine20.com/81/?L=1#tine-20-software) explains that there are limitations on the number of users of the software, unless it is paid for.

I am also having a hard time finding the source code for Tine. [This ](https://packages.tine20.com/maintenance/source/) seems to be a directory of its versions, however this is not ideal source code.

**Comment by nodiscc** [comment]
The source is downloadable here https://packages.tine20.com/maintenance/source/
The `current` archive contains a LICENSE file: http://pastebin.com/raw/6VBAxBGn.
So it is GPL/BSD/AGPL/LGPL.
Listing it as AGPLv3 makes sense since it's the most restrictive license of the 4.
