### ISSUE TITLE
Add OpenMediaVault

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#602]
Self-hosting Solutions
http://www.openmediavault.org/
Sources: https://github.com/openmediavault/openmediavault

>OpenMediaVault is the next generation network attached storage (NAS) solution based on Debian Linux. It contains services like SSH, (S)FTP, SMB/CIFS, DAAP media server, RSync, BitTorrent client and many more.

**Comment by n8225** [comment]
merged with #804
