### ISSUE TITLE
Correct Lite-Reader

### ISSUE THREAD

**Issue by it-praktyk** [Kickball/awesome-selfhosted#612]
The web page Lite-Reader [http://cubny.com/lite-reader/](http://cubny.com/lite-reader/) in the section Feed Readers doesn't exist - a blank page is displayed (not 404).

Is correction action is needed?

Ping: @cubny

**Comment by cubny** [comment]
@it-praktyk will fix it.

**Comment by cubny** [comment]
fixed! @it-praktyk

**Comment by it-praktyk** [comment]
Thank you @cubny .
