### ISSUE TITLE
Find and remove unmaintained projects

### ISSUE THREAD

**Issue by jinformatique** [Kickball/awesome-selfhosted#63]
Hi Edward, I personally found awesome-selfhosted awesome!

It would be nice to sort out new and maintained project over old ones. I know markdown will not be enough to make it possible without duplication and to avoid having to deal with html/js would be easier.

There are so many good project I'd like to install on my server. But the list is simply too long for me.
For example I'll rather try out RedMatrix over Friendica.
Another example, some months ago I wanted to try Jyraphe or Dropcenter. But I found out Jyraphe last updates is from 2010 (ouch) and Dropcenter from 2 years ago. I think they are no longer maintained and for me I don't find it useful to list them.

**Comment by jungle-boogie** [comment]
Hi,

If you find unmaintained projects listed, maybe it's better to remove them all together. 
That's kind of being discussed here:
https://github.com/Kickball/awesome-selfhosted/pull/59

In the case of gallery, though, the developers said they were going to stop working on it. For your software packages, maybe there hasn't been an update in nearly two years. Is that the same? I don't know.

Thanks,
Sean

**Comment by juanito003** [comment]
Ok to remove, but I didn't want to take that kind of decision without talking about it first.

**Comment by jungle-boogie** [comment]
Hello,

Exactly, we should wait for maintainer to advise how long a project should be unmaintained for before removing/not listing.

Thanks,
sean

**Comment by nodiscc** [comment]
I think projects with 1.5+ years without updates or sign of life from developers should be removed. In the case of extremely simple software (very low complexity, low maintenance, just works, no grave bugs), they may be kept in the list.

I prefer keeping software sorted alphabetically, sorting by date would be awful to maintain.

**Comment by Kickball** [comment]
Agreeing with @nodiscc here, unless we automated it there would be no easy way to sort by date, so we should keep sorting alphabetically.

I think once developers say that they are stepping back from development and no replacements are found then the project should be removed.

Also I think that after 6 months with no updates the project should be removed from the list. 

What might be a good idea is to check a different section each week to make sure that all projects in that section are still being maintained. What do you think about that @nodiscc ?

**Comment by jungle-boogie** [comment]
Hi @Kickball,

Could you clarify on this:

> Also I think that after 6 months with no updates the project should be removed from the list.

Updates to what? Their code or a new release? tmux went just over a year between 1.9a and 2.0, but it was very, very actively maintained in their trunk.

Thanks!

**Comment by Kickball** [comment]
@jungle-boogie I was referencing code updates not actual releases, as long as we can see that the project is being maintained and still works then I see no reason to remove it from the list.

**Comment by nodiscc** [comment]
Hi everyone, 6-12 months without code updates seems reasonable. It should not be a hard rule (if there's still activity on mailing lists, bug trackers, project forums, etc.)

> might be a good idea is to check a different section each week to make sure that all projects in that section are still being maintained

Yes that would be great. If projects have commits/releases RSS feeds (github projects do), we could automate tests to ensure they are still active.

**Comment by Kickball** [comment]
What would be the best way to test project's RSS feeds?

Ideally the tests would run automatically, would notify us if the applications are considered dead, and would automatically grab new github repo as they are added to the list.

**Comment by nodiscc** [comment]
I've added the 6-12 months activity requirement to the Contributing section. I'll think about RSS feesd parsing, using Github's API is another option (https://developer.github.com/v3/repos/statistics/ ?). If someone has a ready-made solution for this then please let us know.

**Comment by Kickball** [comment]
Over Christmas I'll try to create a quick application which will grab any github URLs in this repo and get their last update date. 

We can then add a tag (⚠ for example) which would signify 6+ months of Github Inactivity.

**Comment by Kickball** [comment]
I've written a quick script with the help of @AndyR207.

It will be setup to run once a week on a Monday and will create an issue tagged under the [Unmaintained Project Weekly Check](https://github.com/Kickball/awesome-selfhosted/milestones) milestone.

At some point in the near future I will create a repo with the sanitised version of the code.

**Comment by nodiscc** [comment]
:+1: looking forward to it. Keep in mind that some projects do their work in non-default branches (eg `dev` branch, whereas `master` is not updated). But if the default branch has not been updated in a long time, it should be safe to assume that the project is unmaintained.

**Comment by AndyR207** [comment]
The script should work across all branches. So that shouldn't be an issue.






On Thu, Dec 17, 2015 at 3:06 PM -0800, "nodiscc" <notifications@github.com> wrote:





:+1: looking forward to it. Keep in mind that some projects do their work in non-default branches (eg `dev` branch, whereas `master` is not updated). But if the default branch has not been updated in a long time, it should be safe to assume that the project is unmaintained.

---

**Comment by Kickball** [comment]
#381 is the first run of the script to find dead repos.

There are a lot more dead repos than I'd imagined there would be.

**Comment by nodiscc** [comment]
Known unmaintained projects have been removed as part of https://github.com/Kickball/awesome-selfhosted/issues/381. Feel free to report any other you may find.

In the future it should be possible to auto-detect the date of last updates to linked projects. We probably need to start working on https://github.com/Kickball/awesome-selfhosted/issues/1038 to ease automation and make it reliable.
