### ISSUE TITLE
Add Webtrees

### ISSUE THREAD

**Issue by n8225** [Kickball/awesome-selfhosted#635]
Homepage: [https://www.webtrees.net/index.php/en/](https://www.webtrees.net/index.php/en/)
Source Code: [https://github.com/fisharebest/webtrees](https://github.com/fisharebest/webtrees)
webtrees is the web's leading on-line collaborative genealogy application.
GPLv3
PHP

I wasn't sure about creating a category for 1 item. Or possible a subcat?
edit: fixed links

**Comment by nodiscc** [comment]
@n8225 your links' markdown syntax is broken.

It doesn't really fit in any other category. I think it's fine to Create a Genealogy category.
