### ISSUE TITLE
Add Spreed - WebRTC  videoconference software 

### ISSUE THREAD

**Issue by lheckemann** [Kickball/awesome-selfhosted#645]
[Spreed](https://www.spreed.me/) is libre (AGPL) videoconference software that can be accessed through the browser. Seeing as it uses WebRTC — a somewhat established standard, I'm not sure it's quite "Custom"? But it would look kind of lonely in a WebRTC section that it has entirely to itself. Thoughts?

**Comment by n8225** [comment]
I would say Communications under the custom subcat.  Or possible new webrtc subcat and move Jitsy.

**Comment by nodiscc** [comment]
> Communications under the custom subcat

This until more WebRTC solutions are added.

**Comment by Kickball** [comment]
Added in #782.
