### ISSUE TITLE
Wheatbin and RSSPBRRY

### ISSUE THREAD

**Issue by concepthacker** [Kickball/awesome-selfhosted#658]
Makes you hungry just reading the title, eh.

Two github repos I don't see on this mega list are Wheatbin project management software: https://github.com/wheatbin/wheatbin and RSSPBRRY feed reader app: https://github.com/rsspbrry/rsspbrry

Do they not qualify?

**Comment by nodiscc** [comment]
@concepthacker Yes it seems they qualify.

**Comment by n8225** [comment]
added with #793
