### ISSUE TITLE
Add Icecast 2 to Video streaming category as well

### ISSUE THREAD

**Issue by ePirat** [Kickball/awesome-selfhosted#660]
Please add the Icecast 2 streaming server to the video streaming category as well,
as it is capable of video streaming, not only audio streaming.

**Comment by nodiscc** [comment]
@ePirat it is not advertised as suche

http://www.icecast.org/:

> Icecast is a streaming media server which currently supports Ogg (Vorbis and Theora), Opus, WebM and MP3 audio streams.
> It can be used to create an Internet radio station or a privately running jukebox and many things in between. It is very versatile in that new formats can be added relatively easily and supports open standards for communication and interaction.

**Comment by ePirat** [comment]
The “audio streams” refers to MP3, not the other formats, after all Theora is a video codec. But I agree, that is phrased in a very confusing manner and I will make sure to change it.
I can confirm that Icecast is definitely able to stream video.

**Comment by nodiscc** [comment]
Ok good to know. Can you change the description to `streaming audio/video server ` and duplicate the entry into the Video Streaming section? Thanks

**Comment by Kickball** [comment]
Closed in #663.
