### ISSUE TITLE
Awesome Selfhosted Chat

### ISSUE THREAD

**Issue by Kickball** [Kickball/awesome-selfhosted#709]
@GnstheGrain you mentioned a chat system for awesome-selfhosted in your wiki edits. We've setup a selfhosted chat solution, you can signup here: https://chat.awesome-selfhosted.com. Feel free to sign up.

**Comment by GnstheGrain** [comment]
Awesome. Thanks for taking my suggestion into consideration. Account Created. 
This will definitely help in making this repo even more "curated"
