### ISSUE TITLE
Add 99ko

### ISSUE THREAD

**Issue by n8225** [Kickball/awesome-selfhosted#761]
Add 99ko
- [99ko CMS](http://www.99ko.org/) - 99ko allows you to create a website in minutes without knowledge of Web development. It does not use a database server but relies on simple text files (JSON format) to store your data. ([Source Code](https://github.com/j84/99ko)) `PHP`

PR #725 removed 99ko due to lack of a license.
j84/99ko#5 requested the author to add a license.

**Comment by worldworm** [comment]
Hi @n8225 
the Repo link isn't available any more. Can you find a new one or is this projekt dead?
On the website i couldn't find really helpful information..

**Comment by nodiscc** [comment]
Couldn't find anything either the last time I checked, closing. Please reopen if you have new information on 99ko.
