### ISSUE TITLE
Docker and links on the list...

### ISSUE THREAD

**Issue by gissehel** [Kickball/awesome-selfhosted#787]
This is a proposal for discussion. if accepted, I may contribute with several such links for some open source softwares already in the list.
 
As I suppose a lot of people interested in selfhosted apps are also interested in docker, I would feel usefull if in addition to "**Demo**" and "**Source Code**" there was a "**Docker**" link.

The link would point to a docker hub's url or a github's page explaining how to start the image.
If the image is a binary available on the docker hub, it *should* be an automated build.

If several images exists, I *would rather* prefer the image that works from scratch without any configuration, and in the same time lets you customize whatever you want with right (=minimal) configuration, rather than any other criterias (like the smallest image [1], or the image based on your prefered distribution).

[1]: Example [microbox/gogs](https://hub.docker.com/r/microbox/gogs) is awsomely small. And can't clone https repos because it doesn't contains curl. [gogs/gogs](https://hub.docker.com/r/gogs/gogs) just works fine.

**Comment by nodiscc** [comment]
Each software's documentation usually has information on available install methods (from sources, binaries, distro packages, pip, npm, docker, vagrant, VMs, ansible galaxy, sanstorm apps, stable vs dev/beta... etc etc) which we leave to them to document, as we're not going to list them all (considering we use a markdown file). Also pointing to/recommending unreviewed/unofficial docker images would not be great - even more based on subjective/arbitrary criteria (works from scratch/minimal/fast/...).

I suggest contacting each project to help improve their documentation, point to available images/installers etc. instead.

Thank you, I'm closing this but feel free to reopen.

**Comment by Kickball** [comment]
I agree mostly with @nodiscc but think that regardless we should move the discussion to our [chat](https://chat.awesome-selfhosted.com/).
