### ISSUE TITLE
Add visualCaptcha

### ISSUE THREAD

**Issue by Kickball** [Kickball/awesome-selfhosted#788]
Replaces ~~#541~~ #448.

**Comment by n8225** [comment]
@Kickball @nodiscc @AndyR207 [visualCaptcha](https://github.com/emotionLoop/visualCaptcha) is available in PHP, Nodejs, Ruby, and Python. How do we want to add this? 4 seperate entries or 1 entry with four languages?

**Comment by nodiscc** [comment]
My vote goes to 1 entry with four languages.

**Comment by Kickball** [comment]
I'm happy for it to be a single entry with the languages formatted as such:

VisualCaptcha - A configurable captcha solution, focusing on accessibility & simplicity whilst maintaining security. (Demo, Source Code) `GPLv3` `PHP/Nodejs/Ruby/Python`

@AndyR207 @nodiscc @n8225 how does that sound?

**Comment by n8225** [comment]
That's the route I was leaning towards.

**Comment by n8225** [comment]
I made a pr for it #832 but I pushed it to the addtravis branch to test

**Comment by Kickball** [comment]
The PR looks good to me.

**Comment by m1guelpf** [comment]
So, as visualCaptcha was added, I think @n8225 should close this...

**Comment by Kickball** [comment]
Added in #851.
