### ISSUE TITLE
closed source apps are not awesome

### ISSUE THREAD

**Issue by n1trux** [Kickball/awesome-selfhosted#8]
Well, as stated on reddit already, my opinion is that closed source apps are not awesome.

What is the point in self-hosting applications when you can't trust them? They could harm the security and integrity of the whole server system.

**Comment by Kickball** [comment]
Although security is a large part of the reasoning behind self hosting I don't believe that it is always the reason for it.

For example even though Plex is a closed source application it is used a fair bit in homelabs and I would say it was even designed for homelabs/selfhosted environments.

What I'm going to do is create a tag or label which will be used to identify the closed source applications in the list, as I don't believe that we should completely disregard them rather, we should just be more cautious of using them

.![Closed Source](http://picresize.com/images/rsz_1rsz_closed-source-tm4.png)

**Comment by Kickball** [comment]
Take a look at [commit 39](https://github.com/Kickball/awesome-selfhosted/commit/11d3957652782149ea06216f002ca0bb03418bb1).

**Comment by Kovah** [comment]
I would recommend using a smaller version of the logo, maybe without the text below as the icon is explained on top.

**Comment by Kickball** [comment]
We're going to be using this once from now on:
![Closed Source](https://cloud.githubusercontent.com/assets/2252004/8065509/c88bd4b2-0ed9-11e5-9af7-b53e437f56e7.png)

**Comment by n1trux** [comment]
could we do it in 16px? Then it would be as high as the font-size...

**Comment by n1trux** [comment]
I got another idea: What about the icon ⊘ (circled slash) or © (copyright sign) behind the app name? So it looks like this:

- [Plex](https://plex.tv/) **⊘** - Plex is a centralized home media playback system with a powerful central server.

I'd really like the icon to be scalable and directly behind the app name so you can easily distinguish free from proprietary apps.

**Comment by Kovah** [comment]
@n1trux :+1:

**Comment by Kickball** [comment]
Alright, I see where you're coming from.

I'm happy to start using the circled slash instead of the previous icon.

I think this will be the final icon.
