### ISSUE TITLE
Add peerflix-server

### ISSUE THREAD

**Issue by Kingbalou** [Kickball/awesome-selfhosted#825]
**Here is the github link to the project:**

[https://github.com/asapach/peerflix-server](https://github.com/asapach/peerflix-server)

**Description :** 
Download torrent file and provide direct link download or direct link streaming (depend of the file's format)

**Infos supp:** 
Based on NodeJs 
Easy to use and customize 
Provide REST API, Docker

**Comment by Kickball** [comment]
[Peerflix](https://github.com/mafintosh/peerflix) seems to be the original project from what I can tell and seems to be more recently updated.

Unless I am missing something we should look at adding Peerflix instead.

**Comment by nodiscc** [comment]
Peerflix itself is a command line bittorrent client. Peerfilx server seems to be a web interface on top of it. Correct?

**Comment by Kingbalou** [comment]
Correct , it will be great to add the peerflix-server solution instead of peerflix , more accurate for self hosted app.

Peerflix alone can be hosted everywhere as peerflix-server but peerflix can't be remote used via something else than ssh

**Comment by n8225** [comment]
Merged with #904
