### ISSUE TITLE
Add Admidio

### ISSUE THREAD

**Issue by ximex** [Kickball/awesome-selfhosted#869]
Homepage: https://www.admidio.org/
Source: https://github.com/Admidio/admidio
License: GPL-2
Language: PHP (HTML/CSS/JavaScript)
Discription: Admidio is a free open source user management system for websites of organizations and groups. The system has a flexible role model so that it’s possible to reflect the structure and permissions of your organization.

**Comment by n8225** [comment]
I'm thinking Human Resources Management (HRM) for the category?

**Comment by greggluhring** [comment]
Remove me. Remove me. Please please please remove me. I asked fairly nicely 
a long long time ago I can't take it


On December 16, 2016 4:15:22 PM n8225 <notifications@github.com> wrote:

I'm thinking Human Resources Management (HRM) for the category?

**Comment by Kickball** [comment]
@n8225 HRM seems like the best category for this.

**Comment by n8225** [comment]
Merged with #909
