### ISSUE TITLE
Add scri.ch

### ISSUE THREAD

**Issue by raphaelbastide** [Kickball/awesome-selfhosted#886]
http://scri.ch/ is a minimal drawing app. It is [open source](https://github.com/lisezmoi/scri.ch) and really useful to sketch an idea or a quick schema. 

Example:
`![cool drawing from scri.ch](https://scri.ch/vhw.png)`
![cool drawing from scri.ch](https://scri.ch/vhw.png)

**Comment by Kickball** [comment]
This was added in #902.
