### ISSUE TITLE
Another Video Streaming Software, Node.js

### ISSUE THREAD

**Issue by moeiscool** [Kickball/awesome-selfhosted#917]
Please add Shinobi to **Video Streaming**.
[Shinobi](https://github.com/moeiscool/Shinobi)

Shinobi : The Open Source CCTV Software

**Comment by nodiscc** [comment]
Pending in https://github.com/Kickball/awesome-selfhosted/issues/917 but no news from the PR's author regarding required changes.

**Comment by n8225** [comment]
Merged in PR #920
