### ISSUE TITLE
[Suggestion] Add ZeroNet

### ISSUE THREAD

**Issue by mdev88** [Kickball/awesome-selfhosted#919]
https://zeronet.io/

Open, free and uncensorable websites, using Bitcoin cryptography and BitTorrent network

I don't know where this should be, since the BitTorrent network is not completely open source, right...?

**Comment by nodiscc** [comment]
https://github.com/Kickball/awesome-selfhosted#custom

**Comment by worldworm** [comment]
This issue can be closed because the page was added with #1166.
@nodiscc

**Comment by nodiscc** [comment]
Thanks
