### ISSUE TITLE
Addition [rancher]

### ISSUE THREAD

**Issue by SangramChavan** [Kickball/awesome-selfhosted#924]
Rancher is an open source project that provides a complete platform for operating Docker in production. It provides infrastructure services such as multi-host networking, global and local load balancing, and volume snapshots. It integrates native Docker management capabilities such as Docker Machine and Docker Swarm. It offers a rich user experience that enables devops admins to operate Docker in production at large scale.
Licensed under the Apache License, Version 2.0

**Comment by nodiscc** [comment]
It would be more appropriate in https://github.com/n1trux/awesome-sysadmin since the purpose is to manage IT infrastructure.

@SangramChavan please report the issue there (mind the repository [contribution guidelines](https://github.com/n1trux/awesome-sysadmin/blob/master/CONTRIBUTING.md))

**Comment by SangramChavan** [comment]
Sure :+1: 
Thank you !!
