### ISSUE TITLE
Addition [twitterfontana]

### ISSUE THREAD

**Issue by SangramChavan** [Kickball/awesome-selfhosted#926]
An open-source alternative for those flash based Twitter fountains, built using HTML5, CSS (SASS) and Javascript. http:// An open-source alternative for those flash based Twitter fountains, built using HTML5, CSS (SASS) and Javascript. http://twitterfontana.com
.com

MIT

**Comment by mightyfree** [comment]
@Kickball Recommend closing this issue. TwitterFontana is now Walls.io/twitter-walls, a SAAS platform with an ad supported / pricing structure.
