### ISSUE TITLE
Add MumbleDJ

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#935]
Sub-item of Mumble, alongside Mumblecop
https://github.com/matthieugrieger/mumbledj
A Mumble bot that plays audio fetched from various media sites.
MIT / Go

**Comment by mightyfree** [comment]
OK to close issue.

**Comment by Kickball** [comment]
While MumbleDJ seems to be added in the b76ce51 commit, I am not able to find it in the current version of the readme file.

**Comment by mightyfree** [comment]
Thanks for catching that. I'll add it now.

**Comment by mightyfree** [comment]
@Kickball On the MumbleDJ GitHub it states "Unfortunately, this project is no longer maintained. Don't expect any responses on bug reports, feature requests, etc." I'll check on forks.

**Comment by Kickball** [comment]
Thanks. I am still confused about how it was not added in the commit.

**Comment by nodiscc** [comment]
Unmaintained.
