### ISSUE TITLE
Add Cachet.

### ISSUE THREAD

**Issue by chopraaa** [Kickball/awesome-selfhosted#944]
[Cachet](http://cachethq.io/) - Cachet is a beautiful and powerful open source status page system. ([Demo](https://demo.cachethq.io/), [Source Code](https://github.com/CachetHQ/Cachet)) `BSD3` `PHP`

**Comment by nodiscc** [comment]
Already listed at https://github.com/n1trux/awesome-sysadmin#status-pages
