### ISSUE TITLE
Bug Reporter

### ISSUE THREAD

**Issue by SangramChavan** [Kickball/awesome-selfhosted#945]
Bugsnag error reporter for Node.js http://bugsnag.com

**Comment by nodiscc** [comment]
@SangramChavan can you point us to the source code ?

**Comment by Kickball** [comment]
@nodiscc I have found this Github account for the company: https://github.com/bugsnag, however, it seems that it just contains the code for their notifiers.

I will close this issue until @SangramChavan replies.
