### ISSUE TITLE
Wiki - Gruik - abandoned project

### ISSUE THREAD

**Issue by nv1t** [Kickball/awesome-selfhosted#948]
Apparently, the developer classified at as abandoned. So... a note with it would be nice :)

![2017-02-01 10_58_38-grena_gruik_ gruik an open-source markdown note-taking web app abandoned pro](https://cloud.githubusercontent.com/assets/1524118/22502523/81b43772-e86d-11e6-92ea-be363e37f27a.png)
(source: https://github.com/grena/gruik)

**Comment by nodiscc** [comment]
Thank you

https://github.com/Kickball/awesome-selfhosted/issues/949
