### ISSUE TITLE
awesome-selfhosted.com SSL certificate expired

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#955]
https://chat.awesome-selfhosted.com/ causes a browser SSL error/warning.

The certificate expired on 02/02/2017 21:42. The current time is 03/02/2017 19:45.

ping @arylatt @Kickball

**Comment by kirillDanshin** [comment]
@Kickball you can use Caddy to fix this issue forever and improve speed of your websites.

**Comment by arylatt** [comment]
Fixed. The reason behind the issue is I messed up the script I have to re-issue the LE certs. Apologies.

**Comment by nodiscc** [comment]
@arylatt the TLS error reappeared :)

**Comment by nodiscc** [comment]
The whole website is down: #1117
