### ISSUE TITLE
Add mStream

### ISSUE THREAD

**Issue by IrosTheBeggar** [Kickball/awesome-selfhosted#977]
I'm actively working on a music streaming server called mStream.  Check it out here:

https://github.com/IrosTheBeggar/mStream

**Comment by Kickball** [comment]
Looks good, thanks for submitting. How far has the project progressed? Is it ready for public use?

**Comment by IrosTheBeggar** [comment]
The project is in a pretty good place. It has all the standard music streaming features, except for album art which I'm actively working on.  I currently use it on my collection of music and audio books

It's also got a few unique features like jukebox mode, which allows other users to control the web client remotely.  

You can see a working version at: http://darncoyotes.mstream.io/

**Comment by n8225** [comment]
What license is mStream released under?  I didn't see one listed on the repo.

**Comment by IrosTheBeggar** [comment]
Sorry, I didn't see this comment.  mStream is under GPLv3

**Comment by Kickball** [comment]
Closed, added in #1063.
