### ISSUE TITLE
Move CC-BY-NC-SA licensed projects to non-free.md

### ISSUE THREAD

**Issue by nodiscc** [Kickball/awesome-selfhosted#983]
Recheck those project licenses and move to non-free.md if they use the Non-Commercial clause (restriction on usage != Free Software).

**Comment by nodiscc** [comment]
Leed is now [AGPLv3](https://github.com/LeedRSS/Leed/blob/master/License-AGPL-3.0.txt)

**Comment by nodiscc** [comment]
MinigalNano is also AGPLv3

**Comment by nodiscc** [comment]
Dropcenter and Cubics-2048 can be safely moved to non-free.md.

**Comment by n8225** [comment]
completed with #1002
