### ISSUE TITLE
Add netdata (server real-time performance and health monitoring)

### ISSUE THREAD

**Issue by EdisAganovic** [Kickball/awesome-selfhosted#991]
netdata is a system for distributed real-time performance and health monitoring. It provides unparalleled insights, in real-time, of everything happening on the system it runs (including applications such as web and database servers), using modern interactive web dashboards.

netdata is fast and efficient, designed to permanently run on all systems (physical & virtual servers, containers, IoT devices), without disrupting their core function.

netdata runs on Linux, FreeBSD, and MacOS.

https://github.com/firehol/netdata

**Comment by n8225** [comment]
@n1trux @nodiscc @Kickball Wouldn't https://github.com/n1trux/awesome-sysadmin be a better fit for netdata?

**Comment by Kickball** [comment]
I believe it would be a better for [Awesome-Sysadmin#monitoring](https://github.com/n1trux/awesome-sysadmin#monitoring). If everyone agrees then we should close this PR and open a new one in awesome-sysadmin.

**Comment by EdisAganovic** [comment]
I agree 👍

**Comment by nodiscc** [comment]
Netdata is already listed at https://github.com/n1trux/awesome-sysadmin#metric--metric-collection
