### ISSUE TITLE
Status of countly

### ISSUE THREAD

**Issue by kbabioch** [Kickball/awesome-selfhosted#992]
I'm not sure what [count.ly](https://count.ly/product/) was in the past, but right now it does not seem to be an analytics tool that I can host for myself. It is some sort of a service that you have to pay for. I guess it should be removed from the list.

**Comment by nodiscc** [comment]
Their homepage states it can be self-hosted (right in the title) - follow the link to https://count.ly/community-edition/. The source is available at https://github.com/Countly/countly-server under the AGPL license.

@kbabioch Does this answer your question?

**Comment by kbabioch** [comment]
@nodisc Yes, thank you very much. I was overwhelmed with all of the _Whatever-as-a-service_ and _these companis are using this service_ bullshit, so hadn't even found the community edition.
