### ISSUE TITLE
Add Vaultier

### ISSUE THREAD

**Issue by edgimar** [Kickball/awesome-selfhosted#998]
Self-hosted team password manager:  http://www.vaultier.org/

**Comment by emrahcetiner** [comment]
vaultier is open source?

**Comment by edgimar** [comment]
Appears to be a BSD-style license -- source is available [here](http://git.rclick.cz/rclick/vaultier.git) and is also cloned by several people on github.

**Comment by e-alfred** [comment]
Horribly outdated, last commit 2 years ago! And the website has an expired certificate since December! Is this really a good project to add to Awesome-selfhosted especially as this is a password manager?

**Comment by petrk94** [comment]
I think this the major problem on open source, they are stopping the development and no one caring longer about that. :/

**Comment by e-alfred** [comment]
@petrk94 No, I don't think so. The also offer a SaaS "solution" on their website with the expired certificate (from Startcom, adds insult to injury nowadays) as you can see here: https://www.vaultier.org/products/

With Open Source, somebody can at least start on from where they stopped. Not possible with closed source software.

**Comment by edgimar** [comment]
@e-alfred I agree with your concern about the project not being recently updated, and also with your point about it being possible to continue work on it.  It seemed to me like this outdated problem was also the case for many of the password-managers that are currently part of the list.  One benefit that Vaultier provides is easy setup via Docker for those who want to try it out or to further develop it.

**Comment by nodiscc** [comment]
Thanks everyone for investigating this. If the project has not received any updates for a long time, it's probably better not to list it: https://github.com/Kickball/awesome-selfhosted/blob/master/.github/CONTRIBUTING.md

> Software with no development activity for 6-12 months may be removed from the list.

We have started removing unmaintained projects but work on this is far from complete: https://github.com/Kickball/awesome-selfhosted/issues/63. Note that extremely simple or non-critical programs that do not require a lot of maintenance can be kept (a password manager is not one of those). Help on this is welcome.

>  It seemed to me like this outdated problem was also the case for many of the password-managers that are currently part of the list

I did not check recently, but if you found unmaintained password managers they should definitely be removed (please open an issue or send a patch).

**Comment by Kickball** [comment]
@nodiscc we should be okay to close this issue now.

**Comment by nodiscc** [comment]
Feel free to reopen if development resumes on vaultier.

>  One benefit that Vaultier provides is easy setup via Docker

Maybe you could look/ask for Docker support on one of the maintained password managers bug trackers
